/* ═══════════════════════════════════════════
   PHRASAL VERBS DATABASE
   Structure: DB_PV[BaseVerb] = { intro, verbs[], questions[] }
═══════════════════════════════════════════ */

const DB_PV = {

  'Break': {
    intro: 'The verb <strong>break</strong> combines with many particles to form phrasal verbs used in everyday English. These are especially common in SSC exams and test your understanding of context.',
    verbs: [
      { pv: 'break out',    def_en: 'To start suddenly (war, fire, disease)',           def_hi: 'अचानक शुरू होना (युद्ध, आग, बीमारी)', example: 'A fire <em>broke out</em> in the warehouse last night.', note: 'Often used for uncontrollable events.' },
      { pv: 'break down',   def_en: 'To stop functioning; to collapse emotionally',     def_hi: 'काम करना बंद करना; भावनात्मक रूप से टूटना', example: 'The car <em>broke down</em> on the highway.', note: 'Also means to analyse something into parts.' },
      { pv: 'break in',     def_en: 'To enter illegally; to interrupt a conversation',  def_hi: 'अवैध रूप से घुसना; बातचीत में बीच में आना', example: 'Thieves <em>broke in</em> while the family was away.', note: 'Also used for training a new employee.' },
      { pv: 'break up',     def_en: 'To end a relationship; to disperse a crowd',       def_hi: 'रिश्ता खत्म करना; भीड़ को तितर-बितर करना', example: 'The couple <em>broke up</em> after a long argument.', note: 'In British English, also means end of school term.' },
      { pv: 'break off',    def_en: 'To end abruptly; to detach a piece',               def_hi: 'अचानक समाप्त करना; टुकड़ा अलग करना', example: 'Negotiations <em>broke off</em> without any agreement.', note: 'Formal usage in diplomatic/business contexts.' },
      { pv: 'break through',def_en: 'To achieve success after difficulty; to penetrate',def_hi: 'कठिनाई के बाद सफलता पाना; आर-पार जाना', example: 'Scientists <em>broke through</em> years of research to find the cure.', note: '' },
      { pv: 'break into',   def_en: 'To enter forcibly; to start a new career/activity',def_hi: 'जबरदस्ती घुसना; नया काम शुरू करना', example: 'She finally <em>broke into</em> the film industry.', note: '' },
      { pv: 'break away',   def_en: 'To escape; to separate from a group',              def_hi: 'भाग जाना; समूह से अलग होना', example: 'The prisoner <em>broke away</em> from the guards.', note: '' },
    ],
    questions: [
      { id:'pv_brk_1', sentence:'The epidemic _____ in the southern region, affecting thousands of people.', correct:'broke out', options:[{verb:'broke out',hint:'अचानक शुरू हुई'},{verb:'broke down',hint:'काम बंद हुई'},{verb:'broke in',hint:'घुस आई'},{verb:'broke off',hint:'अचानक रुकी'}], feedback:'\'Broke out\' is correct for sudden onset of disease/fire/conflict. \'Broke down\' means to stop functioning. \'Broke in\' means to enter illegally. \'Broke off\' means to end abruptly.' },
      { id:'pv_brk_2', sentence:'The peace talks _____ when neither side agreed to the terms.', correct:'broke off', options:[{verb:'broke off',hint:'अचानक रुकी'},{verb:'broke out',hint:'शुरू हुई'},{verb:'broke up',hint:'भंग हुई'},{verb:'broke through',hint:'आगे बढ़ी'}], feedback:'\'Broke off\' specifically means negotiations or talks ending abruptly without resolution. \'Broke up\' is more informal and general.' },
      { id:'pv_brk_3', sentence:'After years of struggle, the young entrepreneur finally _____ the competitive market.', correct:'broke into', options:[{verb:'broke into',hint:'नया क्षेत्र में प्रवेश'},{verb:'broke away',hint:'अलग हो गया'},{verb:'broke through',hint:'आगे बढ़ा'},{verb:'broke in',hint:'घुस आया'}], feedback:'\'Broke into\' is correct when entering a competitive field or new industry. \'Broke through\' also works but implies overcoming a specific barrier, not entering a market.' },
      { id:'pv_brk_4', sentence:'The old generator _____ just as the storm was approaching.', correct:'broke down', options:[{verb:'broke down',hint:'काम बंद हुआ'},{verb:'broke out',hint:'अचानक शुरू हुआ'},{verb:'broke off',hint:'अलग हो गया'},{verb:'broke in',hint:'टूट कर घुसा'}], feedback:'\'Broke down\' is the correct phrase for machinery or equipment ceasing to function. It can also mean a person collapsing emotionally under pressure.' },
      { id:'pv_brk_5', sentence:'The rebel faction _____ from the main political party after a bitter dispute.', correct:'broke away', options:[{verb:'broke away',hint:'अलग हो गया'},{verb:'broke up',hint:'टूट गया'},{verb:'broke off',hint:'अचानक रुका'},{verb:'broke out',hint:'बाहर निकला'}], feedback:'\'Broke away\' specifically means a group separating itself from a larger body (political party, organisation). \'Broke up\' is less specific and more informal.' },
    ]
  },

  'Bring': {
    intro: 'Phrasal verbs with <strong>bring</strong> often relate to causing change, producing results, or introducing something. They appear frequently in SSC reading comprehension and fill-in-the-blank sections.',
    verbs: [
      { pv: 'bring about',  def_en: 'To cause something to happen',                    def_hi: 'किसी चीज़ को घटित करना', example: 'The new policy <em>brought about</em> significant reforms.', note: 'Formal; often used for social/political change.' },
      { pv: 'bring up',     def_en: 'To raise a child; to mention a topic',            def_hi: 'बच्चे का पालन-पोषण; विषय उठाना', example: 'She was <em>brought up</em> in a small village.', note: 'Dual meaning — context decides the sense.' },
      { pv: 'bring out',    def_en: 'To publish/release; to reveal a quality',         def_hi: 'प्रकाशित करना; गुण उजागर करना', example: 'The publisher will <em>bring out</em> his new novel next month.', note: '' },
      { pv: 'bring down',   def_en: 'To reduce; to cause to fall or fail',             def_hi: 'कम करना; गिराना', example: 'The opposition tried to <em>bring down</em> the government.', note: '' },
      { pv: 'bring forward',def_en: 'To move to an earlier time; to propose',          def_hi: 'पहले करना; प्रस्तावित करना', example: 'The meeting was <em>brought forward</em> to Monday.', note: '' },
      { pv: 'bring in',     def_en: 'To introduce a law; to earn money',               def_hi: 'कानून लाना; पैसा कमाना', example: 'The government <em>brought in</em> new regulations last year.', note: '' },
      { pv: 'bring off',    def_en: 'To succeed in doing something difficult',         def_hi: 'कठिन काम में सफल होना', example: 'Against all odds, the team <em>brought off</em> a remarkable victory.', note: 'Informal; similar to "pull off".' },
      { pv: 'bring round',  def_en: 'To persuade; to restore consciousness',           def_hi: 'मनाना; होश में लाना', example: 'The doctor managed to <em>bring round</em> the unconscious patient.', note: '' },
    ],
    questions: [
      { id:'pv_brng_1', sentence:'The new industrial policy _____ a dramatic transformation in the country\'s economy.', correct:'brought about', options:[{verb:'brought about',hint:'कारण बना'},{verb:'brought up',hint:'पाला-पोसा'},{verb:'brought in',hint:'लाया'},{verb:'brought down',hint:'गिराया'}], feedback:'\'Brought about\' means to cause or produce a result. It is formal and widely used in SSC-level sentences about social, economic or political change.' },
      { id:'pv_brng_2', sentence:'The chairman _____ the annual budget meeting from Friday to Wednesday.', correct:'brought forward', options:[{verb:'brought forward',hint:'पहले किया'},{verb:'brought about',hint:'कारण बना'},{verb:'brought in',hint:'शुरू किया'},{verb:'brought off',hint:'सफल रहा'}], feedback:'\'Brought forward\' means to reschedule something to an earlier date/time. Distinguish from \'brought up\' (raised a topic) and \'brought in\' (introduced a rule).' },
      { id:'pv_brng_3', sentence:'Despite fierce resistance, the rebel leader was unable to _____ the coalition government.', correct:'bring down', options:[{verb:'bring down',hint:'गिराना'},{verb:'bring off',hint:'सफल करना'},{verb:'bring about',hint:'कारण बनना'},{verb:'bring round',hint:'मनाना'}], feedback:'\'Bring down\' a government means to cause it to fall from power. \'Bring about\' is more neutral (cause to happen); \'bring off\' means to succeed in something difficult.' },
      { id:'pv_brng_4', sentence:'The crisis actually _____ the best qualities of leadership in her.', correct:'brought out', options:[{verb:'brought out',hint:'उजागर किया'},{verb:'brought up',hint:'उठाया'},{verb:'brought in',hint:'लाया'},{verb:'brought round',hint:'मनाया'}], feedback:'\'Brought out\' is correct when referring to revealing or highlighting a quality in someone. \'Brought up\' means raised a topic or raised a child, not relevant here.' },
      { id:'pv_brng_5', sentence:'It took hours of persuasion, but his friends finally _____ him to their point of view.', correct:'brought round', options:[{verb:'brought round',hint:'मना लिया'},{verb:'brought over',hint:'ले आया'},{verb:'brought up',hint:'विषय उठाया'},{verb:'brought off',hint:'सफल हुआ'}], feedback:'\'Brought round\' (also \'brought around\') means to persuade someone to change their opinion. It also means to restore someone to consciousness.' },
    ]
  },

  'Call': {
    intro: 'Phrasal verbs with <strong>call</strong> are extremely common in formal and informal English. They appear frequently in cloze tests and sentence completion in SSC and banking exams.',
    verbs: [
      { pv: 'call off',    def_en: 'To cancel something planned',                       def_hi: 'रद्द करना', example: 'The match was <em>called off</em> due to heavy rain.', note: 'Very common in SSC cloze tests.' },
      { pv: 'call on',     def_en: 'To visit someone; to request/appeal to someone',    def_hi: 'किसी से मिलना; अपील करना', example: 'The Prime Minister <em>called on</em> citizens to conserve water.', note: 'Formal usage in speeches and reports.' },
      { pv: 'call for',    def_en: 'To demand or require; to collect someone',          def_hi: 'मांग करना; आवश्यक होना', example: 'The situation <em>calls for</em> immediate action.', note: '' },
      { pv: 'call up',     def_en: 'To phone someone; to summon for military service',  def_hi: 'फ़ोन करना; सेना में बुलाना', example: 'He was <em>called up</em> for military service at the age of 18.', note: '' },
      { pv: 'call in',     def_en: 'To ask to come; to phone in (to work/radio)',       def_hi: 'बुलाना; फ़ोन पर सूचित करना', example: 'The manager <em>called in</em> an expert to assess the damage.', note: '' },
      { pv: 'call out',    def_en: 'To shout; to summon emergency services; to challenge', def_hi: 'पुकारना; आपातकालीन सेवाएं बुलाना; चुनौती देना', example: 'The union <em>called out</em> its members for a strike.', note: '' },
      { pv: 'call back',   def_en: 'To phone again; to recall a product',               def_hi: 'वापस फ़ोन करना; उत्पाद वापस लेना', example: 'The company <em>called back</em> thousands of defective vehicles.', note: '' },
      { pv: 'call upon',   def_en: 'To formally request or appeal (formal of call on)',  def_hi: 'औपचारिक रूप से अनुरोध करना', example: 'The judge <em>called upon</em> the witness to testify.', note: 'More formal than \'call on\'.' },
    ],
    questions: [
      { id:'pv_cal_1', sentence:'The workers\' union threatened to _____ its members if their demands were not met.', correct:'call out', options:[{verb:'call out',hint:'हड़ताल पर बुलाना'},{verb:'call off',hint:'रद्द करना'},{verb:'call up',hint:'फ़ोन करना'},{verb:'call upon',hint:'अनुरोध करना'}], feedback:'\'Call out\' workers means to summon them for a strike. \'Call off\' means to cancel. \'Call up\' means to phone or conscript. The union \'calls out\' its members, not \'calls upon\' in this strike context.' },
      { id:'pv_cal_2', sentence:'The charity event was _____ at the last minute due to the sudden death of the organiser.', correct:'called off', options:[{verb:'called off',hint:'रद्द हुआ'},{verb:'called out',hint:'बाहर बुलाया'},{verb:'called back',hint:'वापस बुलाया'},{verb:'called in',hint:'अंदर बुलाया'}], feedback:'\'Called off\' is the standard phrase for cancelling a planned event, match, meeting or agreement. It is one of the most tested phrasal verbs in SSC cloze tests.' },
      { id:'pv_cal_3', sentence:'The deteriorating law-and-order situation _____ drastic measures by the administration.', correct:'calls for', options:[{verb:'calls for',hint:'आवश्यक है'},{verb:'calls on',hint:'अपील करती है'},{verb:'calls off',hint:'रद्द करती है'},{verb:'calls up',hint:'याद दिलाती है'}], feedback:'\'Calls for\' means demands or requires. When a situation \'calls for\' something, that thing is necessary. \'Calls on\' means to appeal to a person, not to require a course of action.' },
      { id:'pv_cal_4', sentence:'The manufacturer had to _____ over a million units of the product after a safety defect was discovered.', correct:'call back', options:[{verb:'call back',hint:'वापस मंगाना'},{verb:'call off',hint:'रद्द करना'},{verb:'call in',hint:'अंदर बुलाना'},{verb:'call up',hint:'ऊपर बुलाना'}], feedback:'\'Call back\' a product means to recall it from consumers due to a defect or safety issue. This is a very specific business/manufacturing usage.' },
      { id:'pv_cal_5', sentence:'The judge _____ the expert witness to present the forensic evidence before the court.', correct:'called upon', options:[{verb:'called upon',hint:'औपचारिक अनुरोध'},{verb:'called up',hint:'फ़ोन किया'},{verb:'called in',hint:'बुलाया'},{verb:'called out',hint:'नाम पुकारा'}], feedback:'\'Called upon\' is the formal/legal equivalent of \'asked\' — used in official, judicial or formal public contexts. \'Called in\' is more casual (calling in a favour or expert informally).' },
    ]
  },

  'Catch': {
    intro: 'Phrasal verbs with <strong>catch</strong> relate to understanding, reaching, or being affected by something. These are commonly tested in SSC comprehension and vocabulary sections.',
    verbs: [
      { pv: 'catch up',    def_en: 'To reach the same level as others; to learn recent news', def_hi: 'बराबरी करना; ताज़ा खबर पाना', example: 'She studied hard to <em>catch up</em> with the rest of the class.', note: 'Also: catch up with someone = meet after a long time.' },
      { pv: 'catch on',    def_en: 'To become popular; to understand',                   def_hi: 'लोकप्रिय होना; समझना', example: 'The new fashion trend quickly <em>caught on</em> across the country.', note: '' },
      { pv: 'catch out',   def_en: 'To discover someone doing something wrong',          def_hi: 'किसी को गलत करते पकड़ना', example: 'The auditor <em>caught out</em> the accountant falsifying records.', note: 'British English; used for exposing deceit.' },
      { pv: 'catch up with',def_en:'To deal with something you have been avoiding; to reach someone',def_hi:'पकड़ लेना; बराबरी करना', example: 'His past mistakes finally <em>caught up with</em> him.', note: 'Common idiom meaning consequences arrive.' },
      { pv: 'catch at',    def_en: 'To try to grab or seize',                           def_hi: 'पकड़ने की कोशिश करना', example: 'The drowning man <em>caught at</em> a floating piece of wood.', note: '' },
      { pv: 'catch off guard', def_en: 'To surprise someone when unprepared',           def_hi: 'अचानक चौंकाना', example: 'The question <em>caught</em> the minister <em>off guard</em>.', note: '' },
    ],
    questions: [
      { id:'pv_ctc_1', sentence:'The new messaging application _____ within weeks of its launch and now has millions of users.', correct:'caught on', options:[{verb:'caught on',hint:'लोकप्रिय हुई'},{verb:'caught up',hint:'बराबर पहुंची'},{verb:'caught out',hint:'पकड़ी गई'},{verb:'caught at',hint:'पकड़ने की कोशिश की'}], feedback:'\'Caught on\' means to become popular or fashionable. It can also mean to understand something (\'I finally caught on to what he was saying\'). Neither \'caught up\' nor \'caught out\' fits this context.' },
      { id:'pv_ctc_2', sentence:'The investigative journalist _____ the politician accepting bribes through a sting operation.', correct:'caught out', options:[{verb:'caught out',hint:'झूठ/गलती पकड़ी'},{verb:'caught on',hint:'समझ गया'},{verb:'caught up',hint:'पहुंच गया'},{verb:'caught at',hint:'पकड़ने की कोशिश की'}], feedback:'\'Caught out\' means to expose someone in a lie or wrongdoing. It is specifically used when deception is uncovered. \'Caught on\' means understood or became popular.' },
      { id:'pv_ctc_3', sentence:'No matter how far he ran, his criminal record eventually _____ him.', correct:'caught up with', options:[{verb:'caught up with',hint:'पकड़ लिया'},{verb:'caught on to',hint:'समझ लिया'},{verb:'caught out',hint:'पकड़ लिया (झूठ)'},{verb:'caught at',hint:'पकड़ने की कोशिश'}], feedback:'\'Catch up with\' in this figurative sense means the consequences of past actions finally affect you. It is a common expression meaning one cannot escape the results of their past behaviour.' },
      { id:'pv_ctc_4', sentence:'After missing two weeks of classes, she had to work extra hard to _____ her classmates.', correct:'catch up with', options:[{verb:'catch up with',hint:'बराबरी करना'},{verb:'catch on to',hint:'समझना'},{verb:'catch out',hint:'पकड़ना'},{verb:'catch at',hint:'पकड़ने की कोशिश'}], feedback:'\'Catch up with\' means to reach the same level as others after falling behind. This is the most common academic/professional usage of the phrasal verb.' },
      { id:'pv_ctc_5', sentence:'The reporter\'s unexpected question completely _____ the spokesperson _____.', correct:'caught off guard', options:[{verb:'caught off guard',hint:'अचानक चौंकाया'},{verb:'caught on',hint:'समझ गया'},{verb:'caught out',hint:'पकड़ लिया'},{verb:'caught up',hint:'फंस गया'}], feedback:'\'Caught off guard\' means to surprise or find someone unprepared. It is common in formal written English, especially in news and report writing.' },
    ]
  },

  'Come': {
    intro: 'Phrasal verbs with <strong>come</strong> are among the most versatile in English. They cover a wide range of meanings from arrival to inheritance to recovery.',
    verbs: [
      { pv: 'come across', def_en: 'To find by chance; to make an impression',         def_hi: 'अचानक मिलना; प्रभाव डालना', example: 'She <em>came across</em> an old letter while cleaning the attic.', note: 'Also: He comes across as arrogant = he seems arrogant.' },
      { pv: 'come about',  def_en: 'To happen or occur',                               def_hi: 'होना, घटित होना', example: 'How did this misunderstanding <em>come about</em>?', note: 'Formal; used in explanatory contexts.' },
      { pv: 'come round',  def_en: 'To regain consciousness; to be persuaded; to visit', def_hi: 'होश में आना; मान जाना; मिलने आना', example: 'She finally <em>came round</em> to accepting their offer.', note: 'Three meanings — context is key.' },
      { pv: 'come up',     def_en: 'To arise; to be mentioned; to approach',           def_hi: 'उभरना; उल्लेख होना', example: 'An unexpected problem <em>came up</em> during the meeting.', note: '' },
      { pv: 'come into',   def_en: 'To inherit; to enter a state or situation',        def_hi: 'विरासत में पाना; स्थिति में आना', example: 'She <em>came into</em> a large fortune after her uncle\'s death.', note: '' },
      { pv: 'come forward',def_en: 'To volunteer information; to offer help',          def_hi: 'जानकारी देना; मदद के लिए आगे आना', example: 'No witness <em>came forward</em> after the incident.', note: '' },
      { pv: 'come off',    def_en: 'To succeed; to become detached; to take place',    def_hi: 'सफल होना; अलग होना; होना', example: 'His plan didn\'t <em>come off</em> as expected.', note: '' },
      { pv: 'come up with',def_en: 'To suggest or produce an idea or solution',        def_hi: 'विचार/हल प्रस्तुत करना', example: 'The team <em>came up with</em> an innovative solution.', note: 'Very common in business contexts.' },
    ],
    questions: [
      { id:'pv_com_1', sentence:'While going through old files, the researcher _____ a previously unpublished manuscript.', correct:'came across', options:[{verb:'came across',hint:'अचानक मिला'},{verb:'came upon',hint:'अचानक पहुंचा'},{verb:'came forward',hint:'आगे आया'},{verb:'came about',hint:'हुआ'}], feedback:'\'Came across\' means to find or encounter something unexpectedly. \'Came upon\' is also correct but less common in modern usage. \'Came about\' means to happen, not to find.' },
      { id:'pv_com_2', sentence:'After hours of brainstorming, the marketing team finally _____ a catchy slogan.', correct:'came up with', options:[{verb:'came up with',hint:'सुझाया'},{verb:'came up',hint:'उभरा'},{verb:'came across',hint:'मिला'},{verb:'came off',hint:'सफल हुआ'}], feedback:'\'Came up with\' means to think of or produce an idea, solution, or plan. This is different from \'came up\' (arose/approached) and \'came across\' (found by chance).' },
      { id:'pv_com_3', sentence:'The police appealed to the public, urging anyone with information to _____.', correct:'come forward', options:[{verb:'come forward',hint:'आगे आना'},{verb:'come about',hint:'घटित होना'},{verb:'come across',hint:'अचानक मिलना'},{verb:'come round',hint:'मान जाना'}], feedback:'\'Come forward\' means to volunteer information or step up to help. It is the standard phrase used in police investigations and public appeals. \'Come round\' means to change one\'s opinion or regain consciousness.' },
      { id:'pv_com_4', sentence:'He _____ a substantial inheritance after his grandfather passed away.', correct:'came into', options:[{verb:'came into',hint:'विरासत में पाया'},{verb:'came across',hint:'अचानक मिला'},{verb:'came up with',hint:'सुझाया'},{verb:'came off',hint:'सफल हुआ'}], feedback:'\'Came into\' money or property means to inherit it. \'Came across\' also means finding something, but \'came into\' specifically implies inheritance or formal acquisition.' },
      { id:'pv_com_5', sentence:'The attempted coup did not _____ as the military remained loyal to the government.', correct:'come off', options:[{verb:'come off',hint:'सफल नहीं हुआ'},{verb:'come about',hint:'घटित हुआ'},{verb:'come up',hint:'उभरा'},{verb:'come round',hint:'मान गया'}], feedback:'\'Come off\' means to succeed or happen as planned. \'The plan didn\'t come off\' = the plan failed. \'Come about\' = how something happened. \'Come up\' = arose unexpectedly.' },
    ]
  },

  'Cut': {
    intro: 'Phrasal verbs with <strong>cut</strong> typically involve reducing, stopping, or separating. These are commonly tested in SSC vocabulary and cloze tests.',
    verbs: [
      { pv: 'cut down',  def_en: 'To reduce the amount of something; to fell a tree',  def_hi: 'कम करना; पेड़ काटना', example: 'Doctors advised him to <em>cut down</em> on fatty foods.', note: '' },
      { pv: 'cut off',   def_en: 'To disconnect; to isolate; to interrupt',             def_hi: 'काट देना; अलग करना; रोकना', example: 'The village was <em>cut off</em> by floods for three days.', note: 'Also used for cutting off someone\'s speech.' },
      { pv: 'cut out',   def_en: 'To stop doing something; to remove by cutting',      def_hi: 'बंद करना; काट कर निकालना', example: 'The doctor told him to <em>cut out</em> sugar completely.', note: 'Informal: \'Cut it out!\' = Stop it!' },
      { pv: 'cut back',  def_en: 'To reduce expenditure or activity',                  def_hi: 'खर्च/गतिविधि कम करना', example: 'The company <em>cut back</em> on its advertising budget.', note: 'Similar to \'cut down\' but more often used for budgets.' },
      { pv: 'cut in',    def_en: 'To interrupt; to move in front of a queue/traffic',  def_hi: 'बीच में बोलना; आगे घुसना', example: 'She <em>cut in</em> rudely while he was speaking.', note: '' },
      { pv: 'cut across',def_en: 'To affect or concern many groups; to take a shortcut',def_hi: 'कई वर्गों को प्रभावित करना; शॉर्टकट लेना', example: 'The issue of corruption <em>cuts across</em> all political parties.', note: '' },
      { pv: 'cut short', def_en: 'To end earlier than planned',                        def_hi: 'जल्दी समाप्त करना', example: 'His speech was <em>cut short</em> by a power failure.', note: '' },
    ],
    questions: [
      { id:'pv_cut_1', sentence:'The government had to _____ public spending to manage the fiscal deficit.', correct:'cut back', options:[{verb:'cut back',hint:'खर्च घटाया'},{verb:'cut out',hint:'पूरी तरह बंद किया'},{verb:'cut down',hint:'कम किया'},{verb:'cut off',hint:'काट दिया'}], feedback:'\'Cut back\' specifically relates to reducing spending, production or activity, especially in a budgetary/organisational context. \'Cut down\' is more personal (habits), while \'cut back\' is more formal and business-oriented.' },
      { id:'pv_cut_2', sentence:'The flood waters completely _____ the remote village from the rest of the district.', correct:'cut off', options:[{verb:'cut off',hint:'अलग कर दिया'},{verb:'cut out',hint:'निकाल दिया'},{verb:'cut back',hint:'कम कर दिया'},{verb:'cut across',hint:'पार किया'}], feedback:'\'Cut off\' means to isolate or disconnect. A village or city being \'cut off\' by floods is a very standard usage in SSC reading comprehension passages.' },
      { id:'pv_cut_3', sentence:'The problem of malnutrition _____ class and economic boundaries in the developing world.', correct:'cuts across', options:[{verb:'cuts across',hint:'सभी वर्गों में है'},{verb:'cuts down',hint:'कम करती है'},{verb:'cuts off',hint:'अलग करती है'},{verb:'cuts in',hint:'बीच में आती है'}], feedback:'\'Cuts across\' means to affect or apply to many different groups simultaneously, transcending normal divisions. This is a common phrase in formal/analytical writing.' },
      { id:'pv_cut_4', sentence:'The President\'s tour was _____ due to the outbreak of violence in the capital.', correct:'cut short', options:[{verb:'cut short',hint:'जल्दी समाप्त'},{verb:'cut off',hint:'रद्द'},{verb:'cut back',hint:'कम किया'},{verb:'cut out',hint:'हटाया'}], feedback:'\'Cut short\' means to end something before its planned conclusion. Tours, speeches, careers — all can be \'cut short\'. \'Cut off\' means completely disconnected, not early termination.' },
      { id:'pv_cut_5', sentence:'The auditor was speaking when the chairman _____ to add an important correction.', correct:'cut in', options:[{verb:'cut in',hint:'बीच में बोला'},{verb:'cut across',hint:'पार किया'},{verb:'cut out',hint:'बंद कर दिया'},{verb:'cut off',hint:'रोक दिया'}], feedback:'\'Cut in\' means to interrupt someone\'s speech abruptly. \'Cut off\' also means to interrupt but implies completely stopping someone, while \'cut in\' is breaking into a conversation.' },
    ]
  },

  'Get': {
    intro: 'Phrasal verbs with <strong>get</strong> are among the most frequently tested in competitive exams. They cover movement, progress, relationships and overcoming difficulty.',
    verbs: [
      { pv: 'get across',  def_en: 'To communicate an idea successfully',              def_hi: 'विचार सफलतापूर्वक समझाना', example: 'The teacher struggled to <em>get</em> the concept <em>across</em>.', note: '' },
      { pv: 'get away with',def_en:'To escape punishment for a wrongdoing',            def_hi: 'गलत काम से बच निकलना', example: 'He thought he could <em>get away with</em> cheating in the exam.', note: '' },
      { pv: 'get over',    def_en: 'To recover from illness, loss or shock',           def_hi: 'ठीक होना; उबर जाना', example: 'It took her months to <em>get over</em> the accident.', note: '' },
      { pv: 'get round',   def_en: 'To find a way to avoid a difficulty; to persuade', def_hi: 'कठिनाई से बचना; मनाना', example: 'He found a way to <em>get round</em> the regulations.', note: '' },
      { pv: 'get through', def_en: 'To survive a difficult period; to contact by phone; to pass an exam', def_hi: 'मुश्किल दौर से गुज़रना; परीक्षा पास करना', example: 'I couldn\'t <em>get through</em> to her on the phone.', note: 'Three distinct meanings — check context.' },
      { pv: 'get at',      def_en: 'To imply; to reach; to criticise repeatedly',      def_hi: 'इशारा करना; पहुंचना; आलोचना करना', example: 'What exactly are you <em>getting at</em>?', note: '' },
      { pv: 'get along',   def_en: 'To have a good relationship; to manage',           def_hi: 'अच्छे संबंध रखना; काम चलाना', example: 'The two colleagues <em>got along</em> very well.', note: '' },
      { pv: 'get off',     def_en: 'To leave a vehicle; to escape punishment; to start a journey', def_hi: 'उतरना; सज़ा से बचना; यात्रा शुरू करना', example: 'The accused <em>got off</em> with a minor fine.', note: '' },
    ],
    questions: [
      { id:'pv_get_1', sentence:'Despite his eloquence, the speaker failed to _____ his main argument _____ to the audience.', correct:'get across', options:[{verb:'get across',hint:'समझा पाना'},{verb:'get through',hint:'संपर्क करना'},{verb:'get at',hint:'इशारा करना'},{verb:'get over',hint:'उबरना'}], feedback:'\'Get across\' means to successfully communicate an idea or message to others. \'Get at\' implies hinting at something indirectly, not full communication.' },
      { id:'pv_get_2', sentence:'The corrupt official managed to _____ his fraudulent activities for several years.', correct:'get away with', options:[{verb:'get away with',hint:'बच निकला'},{verb:'get off',hint:'सज़ा से बचा'},{verb:'get round',hint:'टाल दिया'},{verb:'get through',hint:'पार कर गया'}], feedback:'\'Get away with\' means to escape consequences for a wrongdoing. \'Get off\' is similar but implies receiving a lighter punishment in court. \'Get round\' means to bypass a rule.' },
      { id:'pv_get_3', sentence:'After suffering a severe financial loss, it took the company two years to _____ the setback.', correct:'get over', options:[{verb:'get over',hint:'उबर जाना'},{verb:'get through',hint:'गुज़र जाना'},{verb:'get across',hint:'समझाना'},{verb:'get along',hint:'मिलकर चलना'}], feedback:'\'Get over\' a setback, loss, or illness means to recover from it. \'Get through\' a difficult period means to survive it (still in process), while \'get over\' implies complete recovery.' },
      { id:'pv_get_4', sentence:'The lawyers found a technicality to _____ the strict new environmental regulations.', correct:'get round', options:[{verb:'get round',hint:'टाल देना'},{verb:'get off',hint:'छोड़ना'},{verb:'get away with',hint:'बच निकलना'},{verb:'get at',hint:'इशारा करना'}], feedback:'\'Get round\' a rule or law means to find a way to avoid or circumvent it without technically breaking it. This is distinct from \'get away with\' (escaping punishment after breaking a rule).' },
      { id:'pv_get_5', sentence:'The manager kept _____ his junior colleague in every team meeting, creating a hostile environment.', correct:'getting at', options:[{verb:'getting at',hint:'बार-बार आलोचना'},{verb:'getting over',hint:'उबर रहा'},{verb:'getting along',hint:'मिलकर चल रहा'},{verb:'getting off',hint:'छोड़ रहा'}], feedback:'\'Get at\' someone means to repeatedly criticise or harass them. This is different from its other meaning (\'what are you getting at?\' = what are you implying?).' },
    ]
  },

  'Give': {
    intro: 'Phrasal verbs with <strong>give</strong> revolve around surrender, distribution, production and quitting. Highly tested in SSC and banking exams.',
    verbs: [
      { pv: 'give up',    def_en: 'To stop trying; to surrender; to quit a habit',     def_hi: 'हार मान लेना; छोड़ देना', example: 'Despite failures, she refused to <em>give up</em>.', note: 'Most common give phrasal verb in exams.' },
      { pv: 'give in',    def_en: 'To surrender; to yield to pressure',                def_hi: 'दबाव के सामने झुकना', example: 'After hours of negotiation, the management <em>gave in</em> to the workers\' demands.', note: 'Implies yielding under pressure (vs. give up = quitting on your own).' },
      { pv: 'give away',  def_en: 'To reveal a secret; to give for free; to present a bride', def_hi: 'राज़ खोलना; मुफ्त देना', example: 'His nervous expression <em>gave away</em> his guilt.', note: '' },
      { pv: 'give out',   def_en: 'To distribute; to stop functioning; to run out',    def_hi: 'वितरित करना; खत्म हो जाना', example: 'The volunteers <em>gave out</em> food packets to flood victims.', note: 'Three meanings — check context carefully.' },
      { pv: 'give off',   def_en: 'To emit light, heat, smell or gas',                 def_hi: 'प्रकाश, गर्मी, गंध छोड़ना', example: 'The factory <em>gives off</em> toxic fumes into the atmosphere.', note: '' },
      { pv: 'give over',  def_en: 'To stop doing something (British informal); to hand over', def_hi: 'बंद करना; सौंपना', example: 'The area was <em>given over</em> to industrial use.', note: '' },
      { pv: 'give back',  def_en: 'To return something to its owner',                  def_hi: 'वापस करना', example: 'The museum <em>gave back</em> the artefacts to the country of origin.', note: '' },
    ],
    questions: [
      { id:'pv_giv_1', sentence:'The factory chimney _____ large quantities of toxic smoke, violating environmental norms.', correct:'gives off', options:[{verb:'gives off',hint:'उत्सर्जित करता है'},{verb:'gives out',hint:'वितरित करता है'},{verb:'gives away',hint:'मुफ्त देता है'},{verb:'gives up',hint:'छोड़ देता है'}], feedback:'\'Give off\' means to emit or produce something such as heat, light, gas or smell. \'Give out\' means to distribute or to stop functioning — it does not describe emissions.' },
      { id:'pv_giv_2', sentence:'His hesitation and avoiding eye contact immediately _____ his involvement in the crime.', correct:'gave away', options:[{verb:'gave away',hint:'राज़ खोल दिया'},{verb:'gave out',hint:'खत्म हो गया'},{verb:'gave in',hint:'झुक गया'},{verb:'gave up',hint:'हार मान ली'}], feedback:'\'Give away\' a secret means to accidentally reveal it. The phrase is used when a person\'s behaviour reveals hidden information unintentionally. \'Give up\' and \'give in\' are about surrendering, not revealing.' },
      { id:'pv_giv_3', sentence:'After months of pressure from shareholders, the CEO finally _____ and agreed to resign.', correct:'gave in', options:[{verb:'gave in',hint:'दबाव में झुका'},{verb:'gave up',hint:'खुद छोड़ा'},{verb:'gave away',hint:'राज़ खोला'},{verb:'gave out',hint:'थक गया'}], feedback:'\'Gave in\' specifically means yielding to external pressure or persuasion. \'Gave up\' means quitting on your own accord, without necessarily being pressured. The word \'pressure\' in the sentence is the key clue.' },
      { id:'pv_giv_4', sentence:'The charity workers _____ blankets and food to the victims of the earthquake.', correct:'gave out', options:[{verb:'gave out',hint:'वितरित किया'},{verb:'gave away',hint:'मुफ्त दिया'},{verb:'gave off',hint:'उत्सर्जित किया'},{verb:'gave over',hint:'सौंपा'}], feedback:'\'Give out\' means to distribute items to a group of people. \'Give away\' also means to give for free, but \'give out\' is more specific to organised distribution, especially in crisis/relief contexts.' },
      { id:'pv_giv_5', sentence:'Scientists have urged citizens not to _____ hope as new treatments for the disease are being developed.', correct:'give up', options:[{verb:'give up',hint:'उम्मीद न छोड़ें'},{verb:'give in',hint:'झुकें नहीं'},{verb:'give away',hint:'राज़ न खोलें'},{verb:'give out',hint:'खत्म न करें'}], feedback:'\'Give up\' hope means to stop hoping or to abandon one\'s hope. \'Give in\' would imply yielding to despair due to external pressure. \'Give up\' is used for self-initiated abandonment of an effort or feeling.' },
    ]
  },

  'Go': {
    intro: 'Phrasal verbs with <strong>go</strong> are extremely varied and cover progression, deterioration, investigation and elimination. Mastering these is essential for SSC exams.',
    verbs: [
      { pv: 'go through', def_en: 'To experience hardship; to examine carefully; to use up', def_hi: 'कष्ट भोगना; ध्यान से जांचना; खर्च करना', example: 'The committee <em>went through</em> each clause of the contract.', note: 'Three meanings — examine, experience, or use up.' },
      { pv: 'go off',     def_en: 'To explode; to ring (alarm); to stop liking; to go bad', def_hi: 'फटना; बजना; खराब होना; नापसंद हो जाना', example: 'The alarm <em>went off</em> at 6 AM.', note: 'Four meanings — context is essential.' },
      { pv: 'go over',    def_en: 'To review or examine something carefully',           def_hi: 'दोबारा जांचना; समीक्षा करना', example: 'Please <em>go over</em> your answers before submitting.', note: '' },
      { pv: 'go back on', def_en: 'To fail to keep a promise; to retract a statement',  def_hi: 'वादा तोड़ना', example: 'He <em>went back on</em> his promise to reform.', note: '' },
      { pv: 'go in for',  def_en: 'To enter a competition; to enjoy a hobby',           def_hi: 'प्रतियोगिता में भाग लेना; शौक रखना', example: 'She <em>goes in for</em> marathon running.', note: '' },
      { pv: 'go without', def_en: 'To manage despite not having something',             def_hi: 'बिना किसी चीज़ के काम चलाना', example: 'During the drought, the villagers had to <em>go without</em> water for days.', note: '' },
      { pv: 'go under',   def_en: 'To fail (business); to lose consciousness',          def_hi: 'व्यापार डूबना; बेहोश होना', example: 'Several small firms <em>went under</em> during the recession.', note: '' },
      { pv: 'go ahead',   def_en: 'To proceed; to do something despite doubts',        def_hi: 'आगे बढ़ना; शुरू करना', example: 'The project was given the green light to <em>go ahead</em>.', note: '' },
    ],
    questions: [
      { id:'pv_go_1', sentence:'The minister _____ his earlier statement, creating confusion among the public.', correct:'went back on', options:[{verb:'went back on',hint:'वादा तोड़ा'},{verb:'went off',hint:'गुस्सा हुआ'},{verb:'went through',hint:'जांच की'},{verb:'went under',hint:'डूब गया'}], feedback:'\'Went back on\' a statement or promise means to retract it or fail to honour it. This is the standard phrase for breaking a commitment. \'Went off\' in this context could mean became angry (informal) but \'went back on\' is the correct formal answer.' },
      { id:'pv_go_2', sentence:'The bomb disposal team carefully _____ each component of the suspected device.', correct:'went through', options:[{verb:'went through',hint:'जांच की'},{verb:'went over',hint:'समीक्षा की'},{verb:'went off',hint:'फट गया'},{verb:'went in for',hint:'भाग लिया'}], feedback:'\'Went through\' here means to examine carefully and methodically. \'Went over\' also means to review, but \'went through\' implies a more thorough, item-by-item examination.' },
      { id:'pv_go_3', sentence:'Hundreds of small businesses _____ during the economic crisis due to lack of credit.', correct:'went under', options:[{verb:'went under',hint:'बर्बाद हुए'},{verb:'went off',hint:'बंद हो गए'},{verb:'went through',hint:'मुश्किल से गुज़रे'},{verb:'went without',hint:'बिना काम चलाया'}], feedback:'\'Went under\' means to fail financially — to go bankrupt. This is a specific idiom for business failure. \'Went through\' a crisis would mean they experienced it but survived.' },
      { id:'pv_go_4', sentence:'Soldiers in remote postings often have to _____ basic amenities for extended periods.', correct:'go without', options:[{verb:'go without',hint:'बिना गुज़ारा'},{verb:'go through',hint:'कष्ट सहना'},{verb:'go under',hint:'डूबना'},{verb:'go off',hint:'खराब होना'}], feedback:'\'Go without\' means to manage or survive despite lacking something essential. \'Go through\' difficulty means to experience hardship, but does not specifically convey the lack of something.' },
      { id:'pv_go_5', sentence:'Despite objections from some committee members, the board decided to _____ with the acquisition.', correct:'go ahead', options:[{verb:'go ahead',hint:'आगे बढ़ना'},{verb:'go through',hint:'जांचना'},{verb:'go in for',hint:'भाग लेना'},{verb:'go over',hint:'समीक्षा करना'}], feedback:'\'Go ahead\' means to proceed with a plan or action, often despite opposition or doubt. \'Go through\' the acquisition would mean to examine it, not proceed with it.' },
    ]
  },

  'Keep': {
    intro: 'Phrasal verbs with <strong>keep</strong> relate to maintaining, continuing, or preventing. These appear frequently in SSC grammar and vocabulary questions.',
    verbs: [
      { pv: 'keep up',      def_en: 'To maintain the same level or pace',              def_hi: 'गति/स्तर बनाए रखना', example: 'He struggled to <em>keep up</em> with the pace of the class.', note: '' },
      { pv: 'keep back',    def_en: 'To withhold information; to prevent from moving forward', def_hi: 'जानकारी छुपाना; रोकना', example: 'The police <em>kept back</em> the details of the investigation.', note: '' },
      { pv: 'keep on',      def_en: 'To continue doing something; to retain an employee', def_hi: 'जारी रखना; कर्मचारी रखना', example: 'Despite the setbacks, she <em>kept on</em> fighting.', note: '' },
      { pv: 'keep up with', def_en: 'To stay informed about; to remain at the same level', def_hi: 'जानकारी रखना; बराबरी करना', example: 'It is hard to <em>keep up with</em> the latest developments in AI.', note: '' },
      { pv: 'keep off',     def_en: 'To avoid; to stay away from',                     def_hi: 'दूर रहना; परहेज़ करना', example: 'The sign said, "Keep off the grass."', note: '' },
      { pv: 'keep in',      def_en: 'To confine; to keep a child in after school',      def_hi: 'रोकना; अंदर रखना', example: 'The teacher <em>kept</em> the naughty student <em>in</em> after class.', note: '' },
      { pv: 'keep out',     def_en: 'To prevent from entering',                        def_hi: 'अंदर न आने देना', example: 'The heavy curtains <em>kept out</em> the cold.', note: '' },
    ],
    questions: [
      { id:'pv_kp_1', sentence:'The defence lawyer accused the prosecution of _____ crucial evidence from the jury.', correct:'keeping back', options:[{verb:'keeping back',hint:'छुपाना'},{verb:'keeping off',hint:'दूर रखना'},{verb:'keeping out',hint:'बाहर रखना'},{verb:'keeping in',hint:'अंदर रखना'}], feedback:'\'Keeping back\' information means withholding it deliberately. In a legal context, this is a critical phrase. \'Keeping out\' means preventing entry; \'keeping in\' means confining.' },
      { id:'pv_kp_2', sentence:'The developing nation found it difficult to _____ the rapid technological advances of richer countries.', correct:'keep up with', options:[{verb:'keep up with',hint:'बराबरी करना'},{verb:'keep up',hint:'बनाए रखना'},{verb:'keep on',hint:'जारी रखना'},{verb:'keep back',hint:'पीछे रहना'}], feedback:'\'Keep up with\' means to remain at the same level as a competitor or to stay informed about something fast-moving. \'Keep up\' is intransitive (no object) while \'keep up with\' requires an object.' },
      { id:'pv_kp_3', sentence:'Doctors advised him to strictly _____ fatty foods and alcohol after his bypass surgery.', correct:'keep off', options:[{verb:'keep off',hint:'परहेज़ करना'},{verb:'keep out',hint:'बाहर रखना'},{verb:'keep back',hint:'रोकना'},{verb:'keep up',hint:'बनाए रखना'}], feedback:'\'Keep off\' something means to avoid it. In a health context, \'keep off\' fatty foods means to abstain from them. \'Keep out\' of something means to not get involved, not to avoid consuming.' },
      { id:'pv_kp_4', sentence:'Despite repeated failures, the determined candidate _____ preparing for the civil services examination.', correct:'kept on', options:[{verb:'kept on',hint:'जारी रखा'},{verb:'kept up',hint:'बनाए रखा'},{verb:'kept back',hint:'रोका'},{verb:'kept off',hint:'दूर रहा'}], feedback:'\'Kept on\' doing something means to continue doing it persistently, especially in the face of difficulty. \'Kept up\' means maintained a standard or pace, which is subtly different.' },
      { id:'pv_kp_5', sentence:'The heavy insulation in the building was designed to _____ the bitter winter cold.', correct:'keep out', options:[{verb:'keep out',hint:'बाहर रखना'},{verb:'keep off',hint:'दूर रखना'},{verb:'keep back',hint:'रोकना'},{verb:'keep in',hint:'अंदर रखना'}], feedback:'\'Keep out\' the cold means to prevent it from entering a space. \'Keep off\' would mean to stay away from the cold oneself, not to prevent it from entering a building.' },
    ]
  },

  'Look': {
    intro: 'Phrasal verbs with <strong>look</strong> are among the richest in English. They cover investigation, care, anticipation and respect — all common in SSC exam contexts.',
    verbs: [
      { pv: 'look into',   def_en: 'To investigate or examine',                        def_hi: 'जांच करना', example: 'The police are <em>looking into</em> the matter.', note: '' },
      { pv: 'look up to',  def_en: 'To respect and admire',                            def_hi: 'सम्मान करना; आदर्श मानना', example: 'Young players <em>look up to</em> national champions.', note: 'Opposite: look down on (to disrespect).' },
      { pv: 'look down on',def_en: 'To consider someone inferior',                     def_hi: 'तुच्छ समझना', example: 'He <em>looks down on</em> anyone without a formal education.', note: '' },
      { pv: 'look after',  def_en: 'To take care of',                                  def_hi: 'देखभाल करना', example: 'She <em>looks after</em> her elderly parents.', note: '' },
      { pv: 'look forward to', def_en: 'To anticipate with pleasure',                  def_hi: 'प्रतीक्षा करना; उत्सुकता से इंतज़ार', example: 'We are <em>looking forward to</em> the conference.', note: 'Always followed by noun or gerund (verb+ing).' },
      { pv: 'look up',     def_en: 'To search for information; to improve',            def_hi: 'जानकारी ढूंढना; सुधरना', example: 'Business prospects are finally <em>looking up</em>.', note: '' },
      { pv: 'look out',    def_en: 'To be careful; to watch for danger',               def_hi: 'सावधान रहना', example: '<em>Look out!</em> There\'s a car coming.', note: '' },
      { pv: 'look on',     def_en: 'To watch without participating',                   def_hi: 'तमाशबीन बनना', example: 'Bystanders merely <em>looked on</em> as the fight escalated.', note: '' },
    ],
    questions: [
      { id:'pv_lk_1', sentence:'The Central Bureau of Investigation has been asked to _____ the alleged financial irregularities.', correct:'look into', options:[{verb:'look into',hint:'जांच करना'},{verb:'look after',hint:'देखभाल करना'},{verb:'look up',hint:'खोजना'},{verb:'look over',hint:'सरसरी जांच'}], feedback:'\'Look into\' means to investigate formally. This is the standard phrase in official/legal/journalistic contexts. \'Look over\' means a quick, less formal review, not a proper investigation.' },
      { id:'pv_lk_2', sentence:'The new recruits _____ the senior officer, who had won multiple awards for bravery.', correct:'looked up to', options:[{verb:'looked up to',hint:'सम्मान करना'},{verb:'looked after',hint:'देखभाल करना'},{verb:'looked into',hint:'जांच करना'},{verb:'looked down on',hint:'तुच्छ समझना'}], feedback:'\'Look up to\' someone means to respect and admire them as a role model. \'Look down on\' is the exact opposite — to consider someone inferior. Both are very commonly confused in SSC.' },
      { id:'pv_lk_3', sentence:'Spectators helplessly _____ as the factory caught fire and collapsed.', correct:'looked on', options:[{verb:'looked on',hint:'तमाशा देखा'},{verb:'looked out',hint:'सावधान रहे'},{verb:'looked after',hint:'देखभाल की'},{verb:'looked up',hint:'ऊपर देखा'}], feedback:'\'Looked on\' means to observe without taking action or getting involved. This is the specific phrase for passive bystanders at an event. \'Looked out\' means to be careful or watch for danger.' },
      { id:'pv_lk_4', sentence:'After years of economic hardship, business conditions in the region are finally _____.', correct:'looking up', options:[{verb:'looking up',hint:'सुधर रहे'},{verb:'looking out',hint:'सावधान है'},{verb:'looking into',hint:'जांच हो रही'},{verb:'looking on',hint:'देख रहे'}], feedback:'\'Looking up\' means improving. When used without an object (\'things are looking up\'), it means conditions are improving. This is an informal but commonly tested usage.' },
      { id:'pv_lk_5', sentence:'The aristocratic family always _____ people from the lower economic strata.', correct:'looked down on', options:[{verb:'looked down on',hint:'तुच्छ समझा'},{verb:'looked up to',hint:'सम्मान किया'},{verb:'looked after',hint:'देखभाल की'},{verb:'looked on',hint:'तमाशा देखा'}], feedback:'\'Look down on\' means to regard someone as inferior or unworthy of respect. It is the opposite of \'look up to\'. Both are classic SSC exam vocabulary items.' },
    ]
  },

  'Make': {
    intro: 'Phrasal verbs with <strong>make</strong> cover understanding, escaping, compensating and constructing. These are tested extensively in competitive English papers.',
    verbs: [
      { pv: 'make out',   def_en: 'To understand or see with difficulty; to claim; to write a cheque', def_hi: 'मुश्किल से समझना; दावा करना', example: 'I could barely <em>make out</em> the words in the dark.', note: 'Three meanings — context is key.' },
      { pv: 'make up',    def_en: 'To invent a story; to reconcile; to constitute; to apply cosmetics', def_hi: 'कहानी बनाना; सुलह करना; बनाना', example: 'She <em>made up</em> an excuse for being late.', note: 'Most versatile phrasal verb in English.' },
      { pv: 'make for',   def_en: 'To move towards; to contribute to',                 def_hi: 'की ओर बढ़ना; योगदान देना', example: 'Good communication <em>makes for</em> a strong team.', note: '' },
      { pv: 'make off',   def_en: 'To escape quickly',                                 def_hi: 'तेज़ी से भाग जाना', example: 'The thieves <em>made off</em> with jewellery worth crores.', note: '' },
      { pv: 'make up for',def_en: 'To compensate for something',                       def_hi: 'क्षतिपूर्ति करना', example: 'She worked extra hours to <em>make up for</em> lost time.', note: '' },
      { pv: 'make do',    def_en: 'To manage with something inadequate',               def_hi: 'कम से काम चलाना', example: 'With no chef available, they had to <em>make do</em> with sandwiches.', note: '' },
      { pv: 'make of',    def_en: 'To understand or form an opinion about',            def_hi: 'समझना; राय बनाना', example: 'What do you <em>make of</em> the new proposal?', note: '' },
    ],
    questions: [
      { id:'pv_mk_1', sentence:'The gang _____ the stolen cash before the police arrived at the scene.', correct:'made off with', options:[{verb:'made off with',hint:'लेकर भाग गई'},{verb:'made out with',hint:'समझा'},{verb:'made up for',hint:'भरपाई की'},{verb:'made for',hint:'की ओर बढ़ी'}], feedback:'\'Made off with\' something means to steal it and escape quickly. \'Made off\' alone means to flee; \'made off with\' means to flee taking something with you. This is a common crime-reporting phrase.' },
      { id:'pv_mk_2', sentence:'His exceptional performance in the final quarter _____ the team\'s earlier poor results.', correct:'made up for', options:[{verb:'made up for',hint:'भरपाई की'},{verb:'made out for',hint:'बना था'},{verb:'made do with',hint:'काम चलाया'},{verb:'made off with',hint:'लेकर गया'}], feedback:'\'Make up for\' means to compensate for something negative. \'Make up\' alone means to invent or reconcile; \'make up for\' specifically means to offset or compensate.' },
      { id:'pv_mk_3', sentence:'Due to the handwriting being smudged, the forensic expert could barely _____ the signature on the document.', correct:'make out', options:[{verb:'make out',hint:'मुश्किल से पढ़ना'},{verb:'make of',hint:'राय बनाना'},{verb:'make up',hint:'बना लेना'},{verb:'make for',hint:'की ओर बढ़ना'}], feedback:'\'Make out\' something means to see or understand it with difficulty. When something is faint, blurry or unclear, you try to \'make it out\'. \'Make of\' means to interpret or form an opinion.' },
      { id:'pv_mk_4', sentence:'During the harsh winter, the flood survivors had to _____ whatever relief material was available.', correct:'make do with', options:[{verb:'make do with',hint:'काम चलाना'},{verb:'make up for',hint:'भरपाई करना'},{verb:'make off with',hint:'लेकर भागना'},{verb:'make out with',hint:'समझना'}], feedback:'\'Make do with\' means to manage or cope with something that is not ideal or sufficient. It suggests resourcefulness under difficult conditions.' },
      { id:'pv_mk_5', sentence:'A stable political environment and transparent policies _____ a conducive business climate.', correct:'make for', options:[{verb:'make for',hint:'योगदान देते हैं'},{verb:'make up',hint:'बनाते हैं'},{verb:'make out',hint:'समझाते हैं'},{verb:'make of',hint:'राय बनाते हैं'}], feedback:'\'Make for\' something means to contribute to or help create a particular condition or result. \'Good policies make for a good environment\' = contribute to. This is a formal, essay-style usage.' },
    ]
  },

  'Put': {
    intro: 'Phrasal verbs with <strong>put</strong> are very commonly tested. They relate to postponing, tolerating, presenting and extinguishing.',
    verbs: [
      { pv: 'put off',    def_en: 'To postpone; to discourage or deter',              def_hi: 'स्थगित करना; हतोत्साहित करना', example: 'The match was <em>put off</em> due to rain.', note: 'Two meanings — postpone or deter/disgust.' },
      { pv: 'put up with',def_en: 'To tolerate something unpleasant',                 def_hi: 'बर्दाश्त करना', example: 'She had to <em>put up with</em> constant interference from her manager.', note: 'Very commonly tested in SSC vocabulary.' },
      { pv: 'put forward',def_en: 'To propose or suggest',                            def_hi: 'प्रस्ताव रखना', example: 'She <em>put forward</em> a radical new approach to the problem.', note: '' },
      { pv: 'put across', def_en: 'To communicate effectively',                       def_hi: 'प्रभावी ढंग से समझाना', example: 'He failed to <em>put across</em> his ideas clearly.', note: 'Similar to \'get across\'.' },
      { pv: 'put out',    def_en: 'To extinguish; to publish; to inconvenience',       def_hi: 'बुझाना; प्रकाशित करना; परेशान करना', example: 'Firefighters quickly <em>put out</em> the blaze.', note: 'Three meanings — fire, publication, inconvenience.' },
      { pv: 'put down',   def_en: 'To criticise; to write down; to put an animal to sleep', def_hi: 'आलोचना करना; लिखना; पशु को euthanize करना', example: 'He constantly <em>puts down</em> his colleagues in meetings.', note: '' },
      { pv: 'put aside',  def_en: 'To save money; to ignore temporarily',             def_hi: 'बचाकर रखना; अनदेखा करना', example: 'She <em>put aside</em> personal differences for the sake of the project.', note: '' },
    ],
    questions: [
      { id:'pv_put_1', sentence:'The long hours and poor working conditions were enough to _____ even the most enthusiastic candidates.', correct:'put off', options:[{verb:'put off',hint:'हतोत्साहित करना'},{verb:'put up with',hint:'बर्दाश्त करना'},{verb:'put down',hint:'आलोचना करना'},{verb:'put out',hint:'परेशान करना'}], feedback:'\'Put off\' in this context means to deter or discourage. \'Put up with\' means to tolerate — the candidates would \'put up with\' conditions, not be \'put off\' by tolerating. \'Put out\' means to extinguish or to inconvenience.' },
      { id:'pv_put_2', sentence:'The committee _____ several innovative solutions to tackle urban flooding.', correct:'put forward', options:[{verb:'put forward',hint:'प्रस्ताव रखा'},{verb:'put across',hint:'समझाया'},{verb:'put out',hint:'प्रकाशित किया'},{verb:'put aside',hint:'अलग रखा'}], feedback:'\'Put forward\' means to propose or suggest ideas, plans or candidates. \'Put across\' means to communicate ideas effectively, which is about how something is explained, not the act of proposing.' },
      { id:'pv_put_3', sentence:'The residents could no longer _____ the incessant noise from the nearby construction site.', correct:'put up with', options:[{verb:'put up with',hint:'बर्दाश्त करना'},{verb:'put off',hint:'स्थगित करना'},{verb:'put down',hint:'आलोचना करना'},{verb:'put out',hint:'बुझाना'}], feedback:'\'Put up with\' is the standard phrase for tolerating an unpleasant situation or behaviour. This is one of the most tested phrasal verbs in SSC vocabulary and cloze tests.' },
      { id:'pv_put_4', sentence:'The fire brigade arrived promptly and _____ the blaze before it could spread further.', correct:'put out', options:[{verb:'put out',hint:'बुझाया'},{verb:'put off',hint:'स्थगित किया'},{verb:'put down',hint:'दबाया'},{verb:'put aside',hint:'अलग किया'}], feedback:'\'Put out\' a fire means to extinguish it. This is the most common usage. \'Put down\' a revolt also means to suppress it, and could work loosely here, but for fire, \'put out\' is the standard answer.' },
      { id:'pv_put_5', sentence:'Despite their personal rivalry, both leaders managed to _____ their differences to address the national crisis.', correct:'put aside', options:[{verb:'put aside',hint:'अनदेखा किया'},{verb:'put off',hint:'स्थगित किया'},{verb:'put up with',hint:'बर्दाश्त किया'},{verb:'put down',hint:'दबाया'}], feedback:'\'Put aside\' differences or grievances means to temporarily ignore or overlook them for a greater purpose. \'Put up with\' implies passive tolerance, while \'put aside\' implies an active, deliberate decision.' },
    ]
  },

  'Run': {
    intro: 'Phrasal verbs with <strong>run</strong> relate to managing, encountering and exhausting. These are vital for SSC reading and vocabulary tests.',
    verbs: [
      { pv: 'run out of',  def_en: 'To have no more of something left',               def_hi: 'खत्म हो जाना', example: 'The hospital <em>ran out of</em> essential medicines during the strike.', note: '' },
      { pv: 'run into',    def_en: 'To meet by chance; to encounter a problem',       def_hi: 'अचानक मिलना; समस्या आना', example: 'The project <em>ran into</em> several technical difficulties.', note: '' },
      { pv: 'run over',    def_en: 'To review quickly; to knock down with a vehicle', def_hi: 'जल्दी से देखना; वाहन से कुचलना', example: 'Let me <em>run over</em> the key points before we conclude.', note: '' },
      { pv: 'run down',    def_en: 'To criticise; to hit with a vehicle; to reduce gradually', def_hi: 'आलोचना करना; टक्कर मारना; धीरे-धीरे कम करना', example: 'The factory was gradually <em>run down</em> before its closure.', note: '' },
      { pv: 'run up',      def_en: 'To accumulate debts or bills',                    def_hi: 'उधार/बिल जमा करना', example: 'He <em>ran up</em> huge debts during the recession.', note: '' },
      { pv: 'run across',  def_en: 'To encounter or find by chance',                  def_hi: 'अचानक मिलना', example: 'She <em>ran across</em> her old school friend at the airport.', note: 'Similar to come across / run into.' },
      { pv: 'run through', def_en: 'To review or rehearse; to use up money quickly',  def_hi: 'जल्दी से दोहराना; खर्च कर देना', example: 'The director <em>ran through</em> the script with the cast.', note: '' },
    ],
    questions: [
      { id:'pv_run_1', sentence:'The relief camp _____ clean drinking water within two days of the flood.', correct:'ran out of', options:[{verb:'ran out of',hint:'खत्म हो गया'},{verb:'ran into',hint:'समस्या आई'},{verb:'ran down',hint:'कम हुआ'},{verb:'ran through',hint:'जल्दी खर्च हुआ'}], feedback:'\'Ran out of\' something means to exhaust one\'s supply of it. \'Ran down\' implies a gradual reduction; \'ran through\' implies using something up quickly due to carelessness or extravagance.' },
      { id:'pv_run_2', sentence:'The infrastructure project _____ numerous bureaucratic hurdles before receiving final clearance.', correct:'ran into', options:[{verb:'ran into',hint:'समस्या आई'},{verb:'ran across',hint:'अचानक मिला'},{verb:'ran out of',hint:'खत्म हो गया'},{verb:'ran up',hint:'जमा हुआ'}], feedback:'\'Ran into\' problems or hurdles means to encounter difficulties unexpectedly during a process. \'Ran across\' is used for people or objects found by chance, not for abstract problems.' },
      { id:'pv_run_3', sentence:'The spendthrift heir _____ enormous debts within a year of inheriting the family fortune.', correct:'ran up', options:[{verb:'ran up',hint:'कर्ज़ जमा किया'},{verb:'ran out of',hint:'खत्म हो गया'},{verb:'ran through',hint:'उड़ा दिया'},{verb:'ran down',hint:'बर्बाद किया'}], feedback:'\'Ran up\' debts or bills means to accumulate them over time. \'Ran through\' a fortune means to spend it all quickly — both are possible here, but \'ran up debts\' is the more specific, idiomatic pairing.' },
      { id:'pv_run_4', sentence:'Before the press conference, the spokesperson _____ the key talking points with the minister.', correct:'ran through', options:[{verb:'ran through',hint:'दोहराया'},{verb:'ran over',hint:'जल्दी देखा'},{verb:'ran down',hint:'आलोचना की'},{verb:'ran across',hint:'अचानक मिला'}], feedback:'\'Ran through\' something means to rehearse or review it in preparation. \'Ran over\' is similar (a quick check), but \'ran through\' is more thorough and implies full coverage, especially before a formal event.' },
      { id:'pv_run_5', sentence:'Critics argued that the government had deliberately _____ the public sector enterprise before privatising it.', correct:'run down', options:[{verb:'run down',hint:'बर्बाद किया'},{verb:'run into',hint:'मुश्किल में डाला'},{verb:'run through',hint:'खर्च किया'},{verb:'run up',hint:'बढ़ाया'}], feedback:'\'Run down\' an institution or enterprise means to gradually reduce its resources and efficiency, often deliberately before closing or selling it. It can also mean to criticise.' },
    ]
  },

  'Set': {
    intro: 'Phrasal verbs with <strong>set</strong> relate to starting, establishing and organising. These appear in SSC sentence completion and error-spotting questions.',
    verbs: [
      { pv: 'set up',    def_en: 'To establish or organise; to falsely incriminate',   def_hi: 'स्थापित करना; झूठा फंसाना', example: 'The government <em>set up</em> a committee to investigate the scam.', note: 'Slang: \'He was set up\' = falsely framed.' },
      { pv: 'set off',   def_en: 'To begin a journey; to trigger; to cause to explode', def_hi: 'यात्रा शुरू करना; चालू करना; विस्फोट करना', example: 'The team <em>set off</em> for the summit at dawn.', note: '' },
      { pv: 'set out',   def_en: 'To begin with a plan; to arrange or display',        def_hi: 'उद्देश्य के साथ निकलना; सजाना', example: 'He <em>set out</em> to reform the corrupt system.', note: '' },
      { pv: 'set aside', def_en: 'To reserve; to disregard; to overturn (legal)',      def_hi: 'अलग रखना; खारिज करना', example: 'The court <em>set aside</em> the lower court\'s verdict.', note: 'Important legal usage.' },
      { pv: 'set back',  def_en: 'To delay; to cost someone a sum of money',           def_hi: 'पीछे धकेलना; खर्च करवाना', example: 'The flood <em>set back</em> the reconstruction effort by months.', note: '' },
      { pv: 'set in',    def_en: 'To begin and seem likely to continue (negative)',    def_hi: 'शुरू होकर जारी रहना (नकारात्मक)', example: 'Panic <em>set in</em> as the situation worsened.', note: 'Always used for unpleasant things: decay, panic, winter.' },
      { pv: 'set about', def_en: 'To begin doing something energetically',             def_hi: 'उत्साह से शुरू करना', example: 'She <em>set about</em> reorganising the entire department.', note: '' },
    ],
    questions: [
      { id:'pv_set_1', sentence:'The Supreme Court _____ the conviction of the accused citing lack of credible evidence.', correct:'set aside', options:[{verb:'set aside',hint:'खारिज किया'},{verb:'set back',hint:'पीछे किया'},{verb:'set up',hint:'स्थापित किया'},{verb:'set out',hint:'निकला'}], feedback:'\'Set aside\' a verdict or conviction means to overturn or nullify it — a specific legal term. \'Set up\' means to establish, not to overturn. This is a very common usage in legal and judicial contexts in SSC.' },
      { id:'pv_set_2', sentence:'Bureaucratic delays _____ the construction of the dam by nearly two years.', correct:'set back', options:[{verb:'set back',hint:'पीछे किया'},{verb:'set off',hint:'शुरू किया'},{verb:'set in',hint:'शुरू हो गई'},{verb:'set aside',hint:'खारिज किया'}], feedback:'\'Set back\' a project or plan means to delay its progress. \'Set in\' would mean the delays themselves began and continued — not that they delayed something else.' },
      { id:'pv_set_3', sentence:'With winter approaching, despair began to _____ among the flood-affected communities.', correct:'set in', options:[{verb:'set in',hint:'घर कर गई'},{verb:'set off',hint:'चालू हुई'},{verb:'set up',hint:'स्थापित हुई'},{verb:'set about',hint:'शुरू की'}], feedback:'\'Set in\' is specifically used for unpleasant conditions (despair, cold, decay, rot) that begin and become established. It is never used for positive things. \'Set off\' means to trigger, which is slightly different.' },
      { id:'pv_set_4', sentence:'The young engineer _____ designing a low-cost water purification system for rural areas.', correct:'set about', options:[{verb:'set about',hint:'शुरू किया'},{verb:'set out',hint:'उद्देश्य से निकला'},{verb:'set up',hint:'स्थापित किया'},{verb:'set off',hint:'रवाना हुआ'}], feedback:'\'Set about\' doing something means to begin it with energy and purpose. \'Set out\' is also possible here (\'set out to design\') but \'set about designing\' is more natural when describing the active process.' },
      { id:'pv_set_5', sentence:'The fire alarm was accidentally _____ when a student lit a match in the corridor.', correct:'set off', options:[{verb:'set off',hint:'चालू हो गया'},{verb:'set up',hint:'स्थापित हुआ'},{verb:'set in',hint:'शुरू हो गया'},{verb:'set out',hint:'रखा गया'}], feedback:'\'Set off\' an alarm means to trigger it. \'Set in\' implies something beginning and continuing, not being triggered by an action. \'Set off\' is the standard phrase for triggering alarms, explosions or reactions.' },
    ]
  },

  'Take': {
    intro: 'Phrasal verbs with <strong>take</strong> are among the most frequently tested in competitive exams. They cover accepting, removing, resembling and beginning.',
    verbs: [
      { pv: 'take up',    def_en: 'To begin a hobby/job; to occupy space/time',       def_hi: 'शुरू करना; जगह/समय लेना', example: 'She <em>took up</em> yoga after her retirement.', note: '' },
      { pv: 'take over',  def_en: 'To assume control of something',                   def_hi: 'कब्ज़ा करना; अधिकार लेना', example: 'The larger company <em>took over</em> its smaller competitor.', note: '' },
      { pv: 'take after', def_en: 'To resemble a parent or relative',                 def_hi: 'माता-पिता जैसा होना', example: 'She <em>takes after</em> her mother in terms of intelligence and wit.', note: '' },
      { pv: 'take off',   def_en: 'To leave the ground; to remove; to become suddenly successful', def_hi: 'उड़ान भरना; उतारना; अचानक सफल होना', example: 'The new product really <em>took off</em> in international markets.', note: 'Three meanings.' },
      { pv: 'take in',    def_en: 'To absorb information; to deceive; to provide shelter', def_hi: 'समझना; धोखा देना; आश्रय देना', example: 'He was completely <em>taken in</em> by the fraudster\'s story.', note: 'Be taken in = to be deceived.' },
      { pv: 'take on',    def_en: 'To hire; to accept work/responsibility; to challenge', def_hi: 'नियुक्त करना; जिम्मेदारी लेना; चुनौती देना', example: 'The firm <em>took on</em> fifty new employees this quarter.', note: '' },
      { pv: 'take back',  def_en: 'To retract a statement; to return goods',          def_hi: 'वापस लेना; वापस करना', example: 'He later <em>took back</em> his controversial remarks.', note: '' },
      { pv: 'take apart', def_en: 'To dismantle; to criticise severely',              def_hi: 'खोलना; कड़ी आलोचना करना', example: 'The journalist <em>took apart</strong> the government\'s claims one by one.', note: '' },
    ],
    questions: [
      { id:'pv_tak_1', sentence:'The multinational corporation _____ three smaller firms last year to expand its market share.', correct:'took over', options:[{verb:'took over',hint:'अधिग्रहण किया'},{verb:'took up',hint:'शुरू किया'},{verb:'took on',hint:'नियुक्त किया'},{verb:'took in',hint:'धोखा दिया'}], feedback:'\'Took over\' means to acquire control of a company or organisation, often through acquisition or merger. \'Took on\' means to hire staff. \'Took in\' means to deceive or to absorb information.' },
      { id:'pv_tak_2', sentence:'Investors were surprised by how quickly the startup\'s new app _____ in Southeast Asian markets.', correct:'took off', options:[{verb:'took off',hint:'अचानक सफल हुआ'},{verb:'took up',hint:'शुरू हुआ'},{verb:'took over',hint:'अधिग्रहण किया'},{verb:'took on',hint:'चुनौती ली'}], feedback:'\'Took off\' means to become suddenly and dramatically successful or popular. This is an informal but very commonly tested meaning. \'Took up\' means to begin something (a hobby/task), not to become successful.' },
      { id:'pv_tak_3', sentence:'The inspector was completely _____ by the elaborate false alibi presented by the suspect.', correct:'taken in', options:[{verb:'taken in',hint:'धोखा खाया'},{verb:'taken off',hint:'उड़ान भरी'},{verb:'taken aback',hint:'चौंक गया'},{verb:'taken up',hint:'व्यस्त हो गया'}], feedback:'\'Taken in\' means to be deceived or fooled. \'Taken aback\' means to be surprised or shocked (a different meaning). \'Taken in\' specifically implies being tricked into believing something false.' },
      { id:'pv_tak_4', sentence:'The new recruits were _____ to handle the surge in customer service demands during the festive season.', correct:'taken on', options:[{verb:'taken on',hint:'नियुक्त किया'},{verb:'taken up',hint:'शुरू किया'},{verb:'taken over',hint:'अधिग्रहण'},{verb:'taken in',hint:'धोखा दिया'}], feedback:'\'Taken on\' employees means to hire them. \'Taken up\' would mean the recruits themselves began something. \'Taken on\' is the correct phrase for the company\'s action of hiring.' },
      { id:'pv_tak_5', sentence:'The opposition leader _____ all the accusations made in the press conference the previous day.', correct:'took back', options:[{verb:'took back',hint:'वापस लिया'},{verb:'took apart',hint:'कड़ी आलोचना'},{verb:'took on',hint:'चुनौती ली'},{verb:'took up',hint:'उठाया'}], feedback:'\'Took back\' statements or accusations means to retract or withdraw them. \'Took apart\' the accusations would mean to dismantle or thoroughly refute them — a plausible but different answer; \'took back\' = formal retraction.' },
    ]
  },

  'Turn': {
    intro: 'Phrasal verbs with <strong>turn</strong> deal with transformation, rejection, production and arrival. These are among the most tested phrasal verbs in SSC exams.',
    verbs: [
      { pv: 'turn down',  def_en: 'To reject; to reduce the volume/heat',             def_hi: 'अस्वीकार करना; कम करना', example: 'The bank <em>turned down</em> his loan application.', note: '' },
      { pv: 'turn up',    def_en: 'To arrive; to appear; to increase volume/heat',    def_hi: 'पहुंचना; बढ़ाना', example: 'He <em>turned up</em> an hour late to the meeting.', note: '' },
      { pv: 'turn out',   def_en: 'To result in; to produce; to attend in numbers',   def_hi: 'निकलना; परिणाम होना; उत्पादन करना', example: 'The event <em>turned out</em> to be a great success.', note: '' },
      { pv: 'turn over',  def_en: 'To give to authorities; to generate revenue; to flip', def_hi: 'सौंपना; राजस्व उत्पन्न करना; पलटना', example: 'The company <em>turns over</em> millions every quarter.', note: '' },
      { pv: 'turn into',  def_en: 'To transform or convert',                          def_hi: 'बदल जाना', example: 'The small protest <em>turned into</em> a full-scale riot.', note: '' },
      { pv: 'turn against',def_en:'To become hostile towards',                        def_hi: 'विरोधी हो जाना', example: 'Public opinion <em>turned against</em> the government after the scandal.', note: '' },
      { pv: 'turn in',    def_en: 'To surrender to police; to go to bed; to submit work', def_hi: 'पुलिस को सौंपना; सोने जाना; जमा करना', example: 'The whistleblower <em>turned in</em> the corrupt official.', note: '' },
    ],
    questions: [
      { id:'pv_trn_1', sentence:'The minor disagreement at the border _____ a full-blown military standoff.', correct:'turned into', options:[{verb:'turned into',hint:'बदल गया'},{verb:'turned out',hint:'निकला'},{verb:'turned over',hint:'पलट गया'},{verb:'turned against',hint:'विरोधी हुआ'}], feedback:'\'Turned into\' means to transform or change into something else — a direct conversion. \'Turned out\' means resulted in, but is more about a final outcome than a transformation process.' },
      { id:'pv_trn_2', sentence:'Despite the controversy, the concert _____ to be a spectacular affair enjoyed by thousands.', correct:'turned out', options:[{verb:'turned out',hint:'साबित हुआ'},{verb:'turned up',hint:'पहुंचा'},{verb:'turned into',hint:'बदल गया'},{verb:'turned over',hint:'पलट गया'}], feedback:'\'Turned out\' means resulted in or proved to be. \'Turned up\' means arrived or appeared. \'Turned into\' implies a transformation, while \'turned out\' describes the final result or impression.' },
      { id:'pv_trn_3', sentence:'The candidate\'s offensive remarks made the electorate _____ him.', correct:'turn against', options:[{verb:'turn against',hint:'विरोधी होना'},{verb:'turn down',hint:'अस्वीकार करना'},{verb:'turn in',hint:'सौंपना'},{verb:'turn out',hint:'निकलना'}], feedback:'\'Turn against\' someone means to become hostile or opposed to them. \'Turn down\' means to reject (an application, offer), not to change allegiance. \'Turn against\' is the correct choice for a shift in opinion.' },
      { id:'pv_trn_4', sentence:'The selection committee _____ his application despite his impressive credentials.', correct:'turned down', options:[{verb:'turned down',hint:'अस्वीकार किया'},{verb:'turned out',hint:'निकला'},{verb:'turned over',hint:'सौंपा'},{verb:'turned in',hint:'जमा किया'}], feedback:'\'Turned down\' means to reject a proposal, application or offer. It is one of the most commonly tested phrasal verbs in SSC. \'Turned in\' means to submit (the opposite of \'turned down\' in this context).' },
      { id:'pv_trn_5', sentence:'The informant agreed to _____ the whereabouts of the fugitive to the authorities.', correct:'turn in', options:[{verb:'turn in',hint:'सूचना सौंपना'},{verb:'turn over',hint:'सौंपना'},{verb:'turn against',hint:'विरोधी होना'},{verb:'turn up',hint:'पहुंचाना'}], feedback:'\'Turn in\' someone means to report them or hand them over to authorities. \'Turn over\' also means to hand over but is more often used for objects or physical evidence. \'Turn in\' is specifically used for informing authorities about a person.' },
    ]
  },

};