/* ═══════════════════════════════════════════
   PREPOSITIONS DATABASE
   Structure: DB_FP[GROUP_NAME] = { intro, words[], questions[] }
   Each group shares the same preposition.
═══════════════════════════════════════════ */

const DB_FP = {

  'Afraid / Aware / Fond / Proud / Ashamed — OF': {
    intro: 'These adjectives all take the preposition <strong>of</strong>. They describe emotions or awareness directed <em>toward</em> something. Confusing these with other prepositions is a classic SSC error.',
    words: [
      { word:'afraid',   preposition:'of', def_en:'Feeling fear or anxiety',        def_hi:'डरा हुआ', example:'She is <em>afraid of</em> making mistakes in public.', note:'' },
      { word:'aware',    preposition:'of', def_en:'Having knowledge or perception',  def_hi:'जागरूक, सचेत', example:'Citizens must be <em>aware of</em> their constitutional rights.', note:'' },
      { word:'fond',     preposition:'of', def_en:'Having affection or liking',      def_hi:'शौकीन', example:'He is very <em>fond of</em> classical music.', note:'' },
      { word:'proud',    preposition:'of', def_en:'Feeling deep pleasure in something', def_hi:'गर्वित', example:'The nation is <em>proud of</em> its armed forces.', note:'' },
      { word:'ashamed',  preposition:'of', def_en:'Feeling guilt or embarrassment',  def_hi:'शर्मिंदा', example:'He was deeply <em>ashamed of</em> his past conduct.', note:'' },
      { word:'capable',  preposition:'of', def_en:'Having the ability to do something', def_hi:'सक्षम', example:'This engine is <em>capable of</em> generating 500 horsepower.', note:'' },
      { word:'independent',preposition:'of',def_en:'Not dependent on others',        def_hi:'स्वतंत्र', example:'She became financially <em>independent of</em> her family.', note:'' },
    ],
    questions: [
      { id:'fp_of_1', sentence:'The whistleblower was not _____ the serious repercussions his testimony would bring.', correct:'aware', options:[{verb:'aware',hint:'जागरूक — of'},{verb:'afraid',hint:'डरा हुआ — of'},{verb:'ashamed',hint:'शर्मिंदा — of'},{verb:'fond',hint:'शौकीन — of'}], feedback:'\'Aware of\' means having knowledge of something. \'Afraid of\' implies fear; the sentence says he was \'not\' aware — he lacked knowledge, not courage. Context eliminates \'afraid\' and \'ashamed\'.' },
      { id:'fp_of_2', sentence:'She is so _____ painting that she spends every weekend in her studio.', correct:'fond', options:[{verb:'fond',hint:'शौकीन — of'},{verb:'proud',hint:'गर्वित — of'},{verb:'capable',hint:'सक्षम — of'},{verb:'ashamed',hint:'शर्मिंदा — of'}], feedback:'\'Fond of\' something means to have a strong liking or affection for it. \'Proud of\' implies achievement, not a hobby or enjoyment. \'Capable of\' implies ability, not preference.' },
      { id:'fp_of_3', sentence:'The investigation revealed that the firm was _____ bypassing safety regulations for years.', correct:'capable', options:[{verb:'capable',hint:'सक्षम — of'},{verb:'aware',hint:'जागरूक — of'},{verb:'ashamed',hint:'शर्मिंदा — of'},{verb:'fond',hint:'शौकीन — of'}], feedback:'\'Capable of\' doing something means having the ability or the tendency to do it (including negative acts). \'Aware of\' would mean they knew about it; \'capable of\' means they were able to do it.' },
      { id:'fp_of_4', sentence:'The retired general is deeply _____ the regiment\'s long history of valour.', correct:'proud', options:[{verb:'proud',hint:'गर्वित — of'},{verb:'fond',hint:'शौकीन — of'},{verb:'aware',hint:'जागरूक — of'},{verb:'independent',hint:'स्वतंत्र — of'}], feedback:'\'Proud of\' is the correct choice when expressing deep satisfaction or pride in an achievement, institution, or association. \'Fond of\' implies affection/liking, not the deeper sense of pride.' },
      { id:'fp_of_5', sentence:'He was _____ his cowardly behaviour during the crisis and refused to speak about it.', correct:'ashamed', options:[{verb:'ashamed',hint:'शर्मिंदा — of'},{verb:'afraid',hint:'डरा हुआ — of'},{verb:'proud',hint:'गर्वित — of'},{verb:'fond',hint:'शौकीन — of'}], feedback:'\'Ashamed of\' means feeling guilt or embarrassment about something done or associated with oneself. \'Afraid of\' means fear about a future event, not guilt about a past action.' },
    ]
  },

  'Addicted / Allergic / Committed / Dedicated — TO': {
    intro: 'These adjectives use the preposition <strong>to</strong> to express attachment, obligation, or physiological response. These are very commonly confused in SSC exams.',
    words: [
      { word:'addicted',   preposition:'to', def_en:'Physically or mentally dependent',   def_hi:'आदी', example:'Millions are <em>addicted to</em> social media platforms.', note:'' },
      { word:'allergic',   preposition:'to', def_en:'Having an adverse reaction',          def_hi:'एलर्जी होना', example:'She is <em>allergic to</em> penicillin.', note:'' },
      { word:'committed',  preposition:'to', def_en:'Dedicated to a cause or course',      def_hi:'समर्पित, वचनबद्ध', example:'The government is <em>committed to</em> poverty eradication.', note:'' },
      { word:'dedicated',  preposition:'to', def_en:'Devoted wholeheartedly',              def_hi:'निष्ठावान', example:'She is fully <em>dedicated to</em> her research.', note:'' },
      { word:'accustomed', preposition:'to', def_en:'Familiar with through habit',         def_hi:'अभ्यस्त', example:'He was not <em>accustomed to</em> such harsh criticism.', note:'' },
      { word:'opposed',    preposition:'to', def_en:'Against or in disagreement',          def_hi:'विरोध में', example:'Many legislators were <em>opposed to</em> the amendment.', note:'' },
      { word:'prone',      preposition:'to', def_en:'Likely to suffer from or do',         def_hi:'प्रवृत्त', example:'The coastal region is <em>prone to</em> cyclones.', note:'' },
    ],
    questions: [
      { id:'fp_to_1', sentence:'The coastal district is particularly _____ flooding during the monsoon season.', correct:'prone', options:[{verb:'prone',hint:'प्रवृत्त — to'},{verb:'addicted',hint:'आदी — to'},{verb:'committed',hint:'वचनबद्ध — to'},{verb:'allergic',hint:'एलर्जी — to'}], feedback:'\'Prone to\' means having a tendency or susceptibility to something, especially negative events. \'Addicted to\' involves habitual behaviour; \'prone to\' is used for natural tendencies or vulnerabilities like flooding.' },
      { id:'fp_to_2', sentence:'Several opposition parties were strongly _____ the privatisation of public sector banks.', correct:'opposed', options:[{verb:'opposed',hint:'विरोध में — to'},{verb:'committed',hint:'समर्पित — to'},{verb:'dedicated',hint:'निष्ठावान — to'},{verb:'accustomed',hint:'अभ्यस्त — to'}], feedback:'\'Opposed to\' means against or in disagreement with a plan or policy. \'Committed to\' and \'dedicated to\' both suggest support, not opposition. Context (\'strongly\' opposed) confirms the answer.' },
      { id:'fp_to_3', sentence:'The new diplomat found it difficult to get _____ the extreme bureaucratic procedures of the host country.', correct:'accustomed', options:[{verb:'accustomed',hint:'अभ्यस्त — to'},{verb:'addicted',hint:'आदी — to'},{verb:'prone',hint:'प्रवृत्त — to'},{verb:'allergic',hint:'एलर्जी — to'}], feedback:'\'Accustomed to\' means to become familiar with or used to something through experience. \'Addicted to\' implies a compulsive habit, not mere familiarity. \'Allergic to\' implies an adverse physical reaction.' },
      { id:'fp_to_4', sentence:'The new party manifesto clearly states that the leadership is _____ implementing electoral reforms.', correct:'committed', options:[{verb:'committed',hint:'वचनबद्ध — to'},{verb:'dedicated',hint:'निष्ठावान — to'},{verb:'opposed',hint:'विरोध में — to'},{verb:'prone',hint:'प्रवृत्त — to'}], feedback:'\'Committed to\' a cause or action implies a formal, public pledge or obligation. \'Dedicated to\' is similar but more personal and emotional. In formal/political contexts, \'committed to\' is the preferred choice.' },
      { id:'fp_to_5', sentence:'The surgeon discovered during the pre-operation screening that the patient was _____ common anaesthetics.', correct:'allergic', options:[{verb:'allergic',hint:'एलर्जी — to'},{verb:'accustomed',hint:'अभ्यस्त — to'},{verb:'prone',hint:'प्रवृत्त — to'},{verb:'addicted',hint:'आदी — to'}], feedback:'\'Allergic to\' means having a physiological adverse reaction to a substance. \'Prone to\' means susceptible, which could work loosely, but \'allergic to\' is the medically precise and contextually appropriate term.' },
    ]
  },

  'Responsible / Famous / Responsible / Notorious — FOR': {
    intro: 'These adjectives take the preposition <strong>for</strong> to express cause, accountability or reputation. A very common source of errors in SSC error-spotting questions.',
    words: [
      { word:'responsible', preposition:'for', def_en:'Being the cause of or accountable for', def_hi:'ज़िम्मेदार', example:'The contractor was held <em>responsible for</em> the bridge collapse.', note:'' },
      { word:'famous',     preposition:'for', def_en:'Well known for a particular quality',  def_hi:'प्रसिद्ध', example:'Agra is <em>famous for</em> the Taj Mahal.', note:'' },
      { word:'notorious',  preposition:'for', def_en:'Famous for something negative',         def_hi:'कुख्यात', example:'The area is <em>notorious for</em> its high crime rate.', note:'' },
      { word:'eligible',   preposition:'for', def_en:'Meeting the requirements for',         def_hi:'पात्र', example:'Only graduates are <em>eligible for</em> this post.', note:'' },
      { word:'grateful',   preposition:'for', def_en:'Feeling thankful',                     def_hi:'आभारी', example:'The team was <em>grateful for</em> the support of the sponsors.', note:'' },
      { word:'sufficient', preposition:'for', def_en:'Enough for a purpose',                 def_hi:'पर्याप्त', example:'The allocated funds were not <em>sufficient for</em> the project.', note:'' },
      { word:'qualified',  preposition:'for', def_en:'Having the right skills or credentials', def_hi:'योग्य', example:'Is she <em>qualified for</em> this managerial role?', note:'' },
    ],
    questions: [
      { id:'fp_for_1', sentence:'The district is _____ its silk weaving industry, which has been thriving for centuries.', correct:'famous', options:[{verb:'famous',hint:'प्रसिद्ध — for'},{verb:'notorious',hint:'कुख्यात — for'},{verb:'responsible',hint:'ज़िम्मेदार — for'},{verb:'grateful',hint:'आभारी — for'}], feedback:'\'Famous for\' is used for positive or neutral renown. \'Notorious for\' is used for negative fame. A silk weaving industry is a positive feature, so \'famous\' is correct. This distinction is a classic SSC trap.' },
      { id:'fp_for_2', sentence:'The drug lord was _____ running one of the largest narcotics smuggling operations in the region.', correct:'notorious', options:[{verb:'notorious',hint:'कुख्यात — for'},{verb:'famous',hint:'प्रसिद्ध — for'},{verb:'responsible',hint:'ज़िम्मेदार — for'},{verb:'eligible',hint:'पात्र — for'}], feedback:'\'Notorious for\' is the correct choice for negative fame or infamy. \'Famous for\' can technically work in informal usage, but in formal/exam contexts, \'notorious\' specifically indicates negative renown.' },
      { id:'fp_for_3', sentence:'Candidates who have not completed their graduation are not _____ the assistant grade examination.', correct:'eligible', options:[{verb:'eligible',hint:'पात्र — for'},{verb:'qualified',hint:'योग्य — for'},{verb:'responsible',hint:'ज़िम्मेदार — for'},{verb:'sufficient',hint:'पर्याप्त — for'}], feedback:'\'Eligible for\' means meeting the minimum criteria or requirements to apply for something. \'Qualified for\' implies having the skills, which is slightly different (one can be eligible without being fully qualified).' },
      { id:'fp_for_4', sentence:'The budget allocated was simply not _____ completing the infrastructure project within the deadline.', correct:'sufficient', options:[{verb:'sufficient',hint:'पर्याप्त — for'},{verb:'eligible',hint:'पात्र — for'},{verb:'responsible',hint:'ज़िम्मेदार — for'},{verb:'grateful',hint:'आभारी — for'}], feedback:'\'Sufficient for\' means adequate or enough for a purpose. \'Eligible for\' relates to qualifications, not quantity. \'Sufficient\' specifically addresses the adequacy of resources (budget, time, material).' },
      { id:'fp_for_5', sentence:'The report concluded that the construction company was wholly _____ the structural failure of the flyover.', correct:'responsible', options:[{verb:'responsible',hint:'ज़िम्मेदार — for'},{verb:'notorious',hint:'कुख्यात — for'},{verb:'famous',hint:'प्रसिद्ध — for'},{verb:'grateful',hint:'आभारी — for'}], feedback:'\'Responsible for\' a failure or accident means being the cause or bearing accountability. \'Notorious for\' would imply the company had a known pattern of failures — possible but \'responsible\' is the precise, direct answer.' },
    ]
  },

  'Anxious / Curious / Angry / Satisfied — ABOUT / WITH / AT': {
    intro: 'These adjectives use different prepositions depending on context and meaning. Mastering these distinctions is critical for SSC error-spotting and fill-in-the-blank questions.',
    words: [
      { word:'anxious',  preposition:'about', def_en:'Worried or concerned',           def_hi:'चिंतित', example:'She is <em>anxious about</em> her upcoming interview.', note:'anxious about = worried; anxious for = eager' },
      { word:'curious',  preposition:'about', def_en:'Eager to know or learn',          def_hi:'जिज्ञासु', example:'Journalists were <em>curious about</em> the minister\'s sudden resignation.', note:'' },
      { word:'angry',    preposition:'with',  def_en:'Feeling anger towards a person', def_hi:'नाराज़ (व्यक्ति पर)', example:'The supervisor was <em>angry with</em> the employee for his negligence.', note:'angry WITH a person; angry AT/ABOUT a situation' },
      { word:'satisfied', preposition:'with', def_en:'Content with a result or person', def_hi:'संतुष्ट', example:'The inspectors were not <em>satisfied with</em> the quality of work.', note:'' },
      { word:'familiar', preposition:'with',  def_en:'Having knowledge of',             def_hi:'परिचित', example:'Are you <em>familiar with</em> the new software?', note:'' },
      { word:'disappointed',preposition:'with',def_en:'Let down by a person or result', def_hi:'निराश', example:'The coach was deeply <em>disappointed with</em> the team\'s performance.', note:'disappointed WITH person/result; disappointed AT/ABOUT an event' },
      { word:'consistent',preposition:'with', def_en:'In agreement with; not contradicting', def_hi:'अनुरूप, सुसंगत', example:'His statement was not <em>consistent with</em> the evidence.', note:'' },
    ],
    questions: [
      { id:'fp_aw_1', sentence:'The forensic report was not _____ the eyewitness accounts provided to the police.', correct:'consistent', options:[{verb:'consistent',hint:'सुसंगत — with'},{verb:'satisfied',hint:'संतुष्ट — with'},{verb:'familiar',hint:'परिचित — with'},{verb:'disappointed',hint:'निराश — with'}], feedback:'\'Consistent with\' means in agreement with or not contradicting. This is a formal usage common in legal, scientific and investigative contexts in SSC exams. \'Satisfied with\' would be an inappropriate meaning here.' },
      { id:'fp_aw_2', sentence:'The quality control team was not _____ the hygiene standards maintained at the food processing plant.', correct:'satisfied', options:[{verb:'satisfied',hint:'संतुष्ट — with'},{verb:'familiar',hint:'परिचित — with'},{verb:'consistent',hint:'सुसंगत — with'},{verb:'angry',hint:'नाराज़ — with'}], feedback:'\'Satisfied with\' means content with the standard or quality of something. \'Familiar with\' would mean they knew about the standards, not that they found them acceptable. Both are \'with\' but the meaning differs.' },
      { id:'fp_aw_3', sentence:'Investigators were naturally _____ the sudden disappearance of financial records from the firm\'s servers.', correct:'curious', options:[{verb:'curious',hint:'जिज्ञासु — about'},{verb:'anxious',hint:'चिंतित — about'},{verb:'angry',hint:'नाराज़ — about'},{verb:'disappointed',hint:'निराश — about'}], feedback:'\'Curious about\' means wanting to know more about something. \'Anxious about\' would imply worry; \'curious about\' implies investigative interest, which fits investigators better.' },
      { id:'fp_aw_4', sentence:'The chief minister was extremely _____ the officials for failing to deliver relief on time.', correct:'angry', options:[{verb:'angry',hint:'नाराज़ — with'},{verb:'disappointed',hint:'निराश — with'},{verb:'satisfied',hint:'संतुष्ट — with'},{verb:'familiar',hint:'परिचित — with'}], feedback:'\'Angry with\' is used when the anger is directed at a person. \'Disappointed with\' is also possible, but the word \'extremely\' and context of \'failing\' suggests a stronger emotion — anger. Also note: angry WITH a person (not \'at\' a person in formal usage).' },
      { id:'fp_aw_5', sentence:'The new IT administrator was not _____ the legacy systems used in the organisation.', correct:'familiar', options:[{verb:'familiar',hint:'परिचित — with'},{verb:'satisfied',hint:'संतुष्ट — with'},{verb:'consistent',hint:'सुसंगत — with'},{verb:'angry',hint:'नाराज़ — with'}], feedback:'\'Familiar with\' something means to have knowledge or experience of it. \'Satisfied with\' means contented. The sentence is about knowledge of a system, so \'familiar\' is the only sensible answer.' },
    ]
  },

  'Differ / Result / Abstain / Benefit — FROM': {
    intro: 'These verbs take the preposition <strong>from</strong> to indicate origin, cause, or source of action. Commonly confused with other prepositions in SSC error-spotting.',
    words: [
      { word:'differ',   preposition:'from', def_en:'To be unlike something else',            def_hi:'अलग होना', example:'His approach <em>differs from</em> conventional methods.', note:'differ FROM = unlike something; differ WITH = disagree with someone' },
      { word:'result',   preposition:'from', def_en:'To be caused by',                        def_hi:'परिणाम होना', example:'The accident <em>resulted from</em> brake failure.', note:'result FROM = caused by; result IN = leads to' },
      { word:'abstain',  preposition:'from', def_en:'To deliberately refrain from',           def_hi:'परहेज़ करना', example:'Three members <em>abstained from</em> voting.', note:'' },
      { word:'refrain',  preposition:'from', def_en:'To stop yourself from doing something',  def_hi:'रोकना', example:'He <em>refrained from</em> commenting on the sensitive issue.', note:'' },
      { word:'benefit',  preposition:'from', def_en:'To gain advantage from',                 def_hi:'लाभ उठाना', example:'Farmers can greatly <em>benefit from</em> the new irrigation scheme.', note:'' },
      { word:'suffer',   preposition:'from', def_en:'To experience pain or a condition',      def_hi:'पीड़ित होना', example:'Millions <em>suffer from</em> malnutrition in developing countries.', note:'' },
      { word:'recover',  preposition:'from', def_en:'To return to a normal state after illness/loss', def_hi:'ठीक होना', example:'The economy is slowly <em>recovering from</em> the recession.', note:'' },
    ],
    questions: [
      { id:'fp_from_1', sentence:'The financial crisis _____ years of irresponsible lending by major banks.', correct:'resulted from', options:[{verb:'resulted from',hint:'कारण था — from'},{verb:'differed from',hint:'अलग था — from'},{verb:'benefited from',hint:'लाभ था — from'},{verb:'suffered from',hint:'पीड़ित था — from'}], feedback:'\'Resulted from\' means was caused by. Distinguish this from \'resulted in\' (which means led to a consequence). \'The crisis resulted FROM lending\' = lending was the cause. \'The crisis resulted IN recession\' = it caused a recession.' },
      { id:'fp_from_2', sentence:'Two of the five board members _____ the crucial vote on the merger proposal.', correct:'abstained from', options:[{verb:'abstained from',hint:'दूर रहे — from'},{verb:'refrained from',hint:'रोके — from'},{verb:'differed from',hint:'अलग थे — from'},{verb:'recovered from',hint:'उबरे — from'}], feedback:'\'Abstained from\' voting is the specific formal/political term for deliberately not participating in a vote. \'Refrained from\' also uses \'from\' but is not the conventional word for electoral/board voting contexts.' },
      { id:'fp_from_3', sentence:'Rural communities stand to greatly _____ the government\'s new rural broadband initiative.', correct:'benefit', options:[{verb:'benefit',hint:'लाभ — from'},{verb:'differ',hint:'अलग — from'},{verb:'recover',hint:'उबरना — from'},{verb:'abstain',hint:'दूर रहना — from'}], feedback:'\'Benefit from\' means to gain advantage or profit from something. \'Recover from\' would mean bouncing back after a setback, not gaining from a new scheme.' },
      { id:'fp_from_4', sentence:'The spokesperson _____ making any statement until the official investigation was complete.', correct:'refrained from', options:[{verb:'refrained from',hint:'रोका — from'},{verb:'abstained from',hint:'परहेज़ किया — from'},{verb:'differed from',hint:'अलग था — from'},{verb:'suffered from',hint:'पीड़ित था — from'}], feedback:'\'Refrained from\' doing something means to consciously stop yourself from doing it. \'Abstained from\' is more formal/political, used for voting or specific ceremonial acts. \'Refrained\' is the natural word for speech and personal conduct.' },
      { id:'fp_from_5', sentence:'The current administration\'s economic model _____ its predecessor\'s in several fundamental ways.', correct:'differs from', options:[{verb:'differs from',hint:'अलग है — from'},{verb:'results from',hint:'परिणाम है — from'},{verb:'suffers from',hint:'पीड़ित है — from'},{verb:'benefits from',hint:'लाभान्वित है — from'}], feedback:'\'Differs from\' means is unlike or in contrast to. This is a critical distinction: \'differ FROM\' = unlike (comparing); \'differ WITH\' = disagree with (debating). \'Results from\' means caused by.' },
    ]
  },

  'Agree / Deal / Begin / Charge — WITH / ON': {
    intro: 'These verbs use <strong>with</strong> or <strong>on</strong> depending on meaning and context — one of the trickiest preposition groups for SSC candidates.',
    words: [
      { word:'agree with',  preposition:'with', def_en:'To have the same opinion as someone', def_hi:'सहमत होना (व्यक्ति से)', example:'I <em>agree with</em> the committee\'s decision.', note:'agree WITH a person or opinion; agree ON a topic/plan; agree TO a proposal' },
      { word:'deal with',   preposition:'with', def_en:'To handle or manage a situation',    def_hi:'निपटना', example:'The administration failed to <em>deal with</em> the water crisis effectively.', note:'' },
      { word:'charge with', preposition:'with', def_en:'To formally accuse of a crime',      def_hi:'आरोप लगाना', example:'The officer was <em>charged with</em> accepting bribes.', note:'' },
      { word:'tamper with', preposition:'with', def_en:'To interfere or meddle with',        def_hi:'छेड़छाड़ करना', example:'The accused was caught <em>tampering with</em> evidence.', note:'' },
      { word:'agree on',    preposition:'on',   def_en:'To reach a joint decision on a topic', def_hi:'विषय पर सहमत होना', example:'The two parties finally <em>agreed on</em> a ceasefire.', note:'' },
      { word:'insist on',   preposition:'on',   def_en:'To demand firmly',                   def_hi:'ज़िद करना', example:'The union <em>insisted on</em> a 15% pay rise.', note:'' },
      { word:'comment on',  preposition:'on',   def_en:'To give an opinion about',           def_hi:'टिप्पणी करना', example:'The minister refused to <em>comment on</em> the allegations.', note:'' },
    ],
    questions: [
      { id:'fp_wo_1', sentence:'The forensic team found evidence that someone had _____ the crime scene before their arrival.', correct:'tampered with', options:[{verb:'tampered with',hint:'छेड़छाड़ की — with'},{verb:'dealt with',hint:'निपटा — with'},{verb:'agreed with',hint:'सहमत हुआ — with'},{verb:'charged with',hint:'आरोप लगाया — with'}], feedback:'\'Tampered with\' means to interfere with or alter something illegally or improperly. This is a specific phrase used in legal/forensic contexts for meddling with evidence.' },
      { id:'fp_wo_2', sentence:'After three days of intense negotiations, both delegations _____ the terms of the bilateral treaty.', correct:'agreed on', options:[{verb:'agreed on',hint:'विषय पर सहमत — on'},{verb:'agreed with',hint:'व्यक्ति से सहमत — with'},{verb:'insisted on',hint:'ज़िद की — on'},{verb:'commented on',hint:'टिप्पणी की — on'}], feedback:'\'Agreed on\' a topic or terms means both parties came to a mutual decision. \'Agreed with\' is used for a person or an opinion. \'The delegations agreed on the terms\' = they jointly reached a decision.' },
      { id:'fp_wo_3', sentence:'The anti-terrorism squad was praised for its ability to swiftly _____ hostile situations.', correct:'deal with', options:[{verb:'deal with',hint:'निपटना — with'},{verb:'tamper with',hint:'छेड़छाड़ — with'},{verb:'charge with',hint:'आरोप लगाना — with'},{verb:'agree with',hint:'सहमत — with'}], feedback:'\'Deal with\' a situation means to handle or manage it. This is one of the most common verb+preposition combinations in English. \'Agree with\' and \'charge with\' have entirely different meanings.' },
      { id:'fp_wo_4', sentence:'The union _____ a minimum wage increase of at least 20% before returning to work.', correct:'insisted on', options:[{verb:'insisted on',hint:'ज़िद की — on'},{verb:'commented on',hint:'टिप्पणी की — on'},{verb:'agreed on',hint:'सहमत हुए — on'},{verb:'dealt with',hint:'निपटे — on'}], feedback:'\'Insisted on\' means to demand something firmly, refusing to back down. \'Agreed on\' would mean they had already reached a decision jointly. \'Insisted\' implies one-sided demand before any agreement.' },
      { id:'fp_wo_5', sentence:'Three senior officials were _____ corruption and abuse of power following the internal inquiry.', correct:'charged with', options:[{verb:'charged with',hint:'आरोपी — with'},{verb:'dealt with',hint:'निपटाया — with'},{verb:'agreed with',hint:'सहमत — with'},{verb:'tampered with',hint:'छेड़छाड़ — with'}], feedback:'\'Charged with\' a crime is the legal/formal term for officially accusing someone of an offence. This is the standard phrasing in legal documents and news reports.' },
    ]
  },

  'Accuse / Approve / Beware / Consist — OF': {
    intro: 'These verbs all take <strong>of</strong> as their preposition. They describe accusation, approval, warning and composition — all commonly tested in SSC.',
    words: [
      { word:'accuse',  preposition:'of', def_en:'To charge someone with a fault/crime', def_hi:'आरोप लगाना', example:'He was <em>accused of</em> embezzlement by the board.', note:'accuse OF a crime (not: accuse for)' },
      { word:'approve', preposition:'of', def_en:'To officially sanction or agree with',  def_hi:'स्वीकृति देना', example:'The committee <em>approved of</em> the new safety protocol.', note:'' },
      { word:'beware',  preposition:'of', def_en:'To be cautious about a danger',         def_hi:'सावधान रहना', example:'Travellers are advised to <em>beware of</em> pickpockets in crowded areas.', note:'' },
      { word:'consist', preposition:'of', def_en:'To be composed of; to be made up of',   def_hi:'मिलकर बनना', example:'The jury <em>consists of</em> twelve members.', note:'consist OF (not: consist with/from)' },
      { word:'deprive', preposition:'of', def_en:'To take away something essential',      def_hi:'वंचित करना', example:'Children in war zones are often <em>deprived of</em> education.', note:'' },
      { word:'dispose', preposition:'of', def_en:'To get rid of; to deal with finally',   def_hi:'निपटाना, फेंकना', example:'The city struggled to <em>dispose of</em> solid waste efficiently.', note:'' },
      { word:'convince',preposition:'of', def_en:'To persuade someone of a truth',        def_hi:'विश्वास दिलाना', example:'The lawyer failed to <em>convince</em> the jury <em>of</em> his client\'s innocence.', note:'' },
    ],
    questions: [
      { id:'fp_of2_1', sentence:'Slum children are routinely _____ access to quality healthcare and education.', correct:'deprived of', options:[{verb:'deprived of',hint:'वंचित — of'},{verb:'accused of',hint:'आरोपी — of'},{verb:'convinced of',hint:'विश्वास दिलाया — of'},{verb:'disposed of',hint:'निपटाया — of'}], feedback:'\'Deprived of\' means to have something essential taken away or withheld. \'Accused of\' means charged with a crime. The context of lacking access confirms \'deprived of\'.' },
      { id:'fp_of2_2', sentence:'The prosecution could not _____ the jury _____ the defendant\'s culpability beyond reasonable doubt.', correct:'convince', options:[{verb:'convince',hint:'विश्वास दिलाना — of'},{verb:'accuse',hint:'आरोप लगाना — of'},{verb:'beware',hint:'सावधान रहना — of'},{verb:'dispose',hint:'निपटाना — of'}], feedback:'\'Convince...of\' means to make someone believe or accept something. In legal contexts, the prosecution tries to convince the jury of guilt. \'Accuse of\' means to charge someone, not to persuade.' },
      { id:'fp_of2_3', sentence:'The municipal authority was criticised for failing to properly _____ the industrial waste.', correct:'dispose of', options:[{verb:'dispose of',hint:'निपटाना — of'},{verb:'consist of',hint:'मिलकर बनना — of'},{verb:'beware of',hint:'सावधान रहना — of'},{verb:'deprive of',hint:'वंचित करना — of'}], feedback:'\'Dispose of\' waste means to get rid of it or manage its removal. This is the standard phrase in environmental and civic contexts. \'Consist of\' means composed of — a completely different meaning.' },
      { id:'fp_of2_4', sentence:'The investigating agency _____ the senior bureaucrat _____ leaking classified documents to a foreign entity.', correct:'accused', options:[{verb:'accused',hint:'आरोप लगाया — of'},{verb:'convinced',hint:'विश्वास दिलाया — of'},{verb:'deprived',hint:'वंचित किया — of'},{verb:'approved',hint:'स्वीकृति दी — of'}], feedback:'\'Accused...of\' a crime is the formal phrase for charging someone. A very common SSC error is using \'accuse for\' — always use \'accuse OF\'. \'Convicted of\' would come after a verdict; \'accused of\' precedes trial.' },
      { id:'fp_of2_5', sentence:'The expert committee _____ the new environmental impact assessment guidelines.', correct:'approved of', options:[{verb:'approved of',hint:'स्वीकृति दी — of'},{verb:'accused of',hint:'आरोप लगाया — of'},{verb:'consisted of',hint:'मिलकर बना — of'},{verb:'disposed of',hint:'निपटाया — of'}], feedback:'\'Approved of\' means to give official sanction or to express agreement with something. Distinguish from \'approved\' (transitive, without \'of\'): \'The board approved the plan\' vs \'The board approved of the direction\'.' },
    ]
  },

  'Confidence / Lack / Shortage / Abundance — IN / OF': {
    intro: 'Nouns expressing quantity, trust or absence take specific prepositions. Mixing these up is one of the most frequent errors in SSC sentence correction questions.',
    words: [
      { word:'confidence', preposition:'in',  def_en:'Trust or belief in someone/something', def_hi:'भरोसा, आस्था', example:'The public has lost <em>confidence in</em> the banking system.', note:'confidence IN; not \'confidence on\'' },
      { word:'interest',   preposition:'in',  def_en:'Attention or curiosity towards',       def_hi:'रुचि', example:'Young voters have shown increasing <em>interest in</em> local governance.', note:'' },
      { word:'lack',       preposition:'of',  def_en:'Absence or shortage of something',     def_hi:'अभाव', example:'A <em>lack of</em> transparency led to the crisis.', note:'lack OF; not \'lack in\'' },
      { word:'shortage',   preposition:'of',  def_en:'Not enough of something essential',    def_hi:'कमी', example:'The region is facing a severe <em>shortage of</em> potable water.', note:'' },
      { word:'abundance',  preposition:'of',  def_en:'A very large quantity of',             def_hi:'बहुतायत', example:'The country has an <em>abundance of</em> natural resources.', note:'' },
      { word:'belief',     preposition:'in',  def_en:'Acceptance that something is true',    def_hi:'विश्वास', example:'Her <em>belief in</em> justice never wavered.', note:'' },
      { word:'deficiency', preposition:'of/in',def_en:'A lack of a required substance',      def_hi:'कमी', example:'A <em>deficiency of</em> vitamin D affects bone health.', note:'deficiency OF or deficiency IN both acceptable.' },
    ],
    questions: [
      { id:'fp_inof_1', sentence:'The investigation highlighted a serious _____ accountability among senior officials.', correct:'lack of', options:[{verb:'lack of',hint:'अभाव — of'},{verb:'shortage of',hint:'कमी — of'},{verb:'abundance of',hint:'बहुतायत — of'},{verb:'deficiency of',hint:'कमी — of'}], feedback:'\'Lack of\' accountability is the idiomatic and standard expression for the absence of a quality or intangible thing. \'Shortage of\' is used more for tangible/quantifiable resources (water, staff, funds), not abstract qualities like accountability.' },
      { id:'fp_inof_2', sentence:'After decades of mismanagement, the general public has lost all _____ the regulatory authorities.', correct:'confidence in', options:[{verb:'confidence in',hint:'भरोसा — in'},{verb:'interest in',hint:'रुचि — in'},{verb:'belief in',hint:'विश्वास — in'},{verb:'lack of',hint:'अभाव — of'}], feedback:'\'Confidence in\' a person or institution means trust in their ability to function properly. \'Belief in\' is also a \'in\' collocation but is more philosophical. \'Confidence in\' is the natural phrase for institutional trust.' },
      { id:'fp_inof_3', sentence:'The country\'s economy benefits greatly from its _____ mineral and petroleum reserves.', correct:'abundance of', options:[{verb:'abundance of',hint:'बहुतायत — of'},{verb:'lack of',hint:'अभाव — of'},{verb:'shortage of',hint:'कमी — of'},{verb:'deficiency of',hint:'कमी — of'}], feedback:'\'Abundance of\' means a very large or more than sufficient quantity of something. The context (\'benefits greatly\') confirms a positive, plentiful scenario — eliminating \'shortage\', \'lack\' and \'deficiency\'.' },
      { id:'fp_inof_4', sentence:'The scheme failed to generate adequate _____ the target demographic.', correct:'interest in', options:[{verb:'interest in',hint:'रुचि — in'},{verb:'confidence in',hint:'भरोसा — in'},{verb:'belief in',hint:'विश्वास — in'},{verb:'lack of',hint:'अभाव — of'}], feedback:'\'Interest in\' something means attention, curiosity or engagement with it. A scheme generating \'interest in\' a demographic means creating curiosity or uptake among them. \'Confidence in\' implies trust, not engagement.' },
      { id:'fp_inof_5', sentence:'The farmers\' agitation was triggered by a severe _____ irrigation water during the dry season.', correct:'shortage of', options:[{verb:'shortage of',hint:'कमी — of'},{verb:'lack of',hint:'अभाव — of'},{verb:'abundance of',hint:'बहुतायत — of'},{verb:'deficiency of',hint:'कमी — of'}], feedback:'\'Shortage of\' is specifically used for tangible, quantifiable resources (water, food, staff) that are insufficient for needs. \'Lack of\' is more abstract. \'Shortage\' implies a quantifiable deficit below what is needed.' },
    ]
  },

};